//////////////////////////////////////////////////////
////	FIND adminUIDandAccess[] =
////	add the following just above the final "" in any/all the types of admin you want to have the function
//////////////////////////////////////////////////////

			
			"==== Bandit Missions ====",
			"Spawn_bandits_Mission",
			"Spawn_bauhaus_Mission",
			"Spawn_beertransport_Mission",
			"Spawn_behindenemylines_Mission",
			"Spawn_blackhawkdown_Mission",
			"Spawn_cardealer_Mission",
			"Spawn_construction_Mission",
			"Spawn_donthasslethehoff_Mission",
			"Spawn_foodtransport_Mission",
			"Spawn_guntransport_Mission",
			"Spawn_humanitarian_Mission",
			"Spawn_lost_battalion_Mission",
			"Spawn_medical_Mission",
			"Spawn_mercbase_Mission",
			"Spawn_mercenaries_Mission",
			"Spawn_nedbandit1_Mission",
			"Spawn_nedbuilding1_Mission",
			"Spawn_nedcar_Mission",
			"Spawn_nedcashbandits_Mission",
			"Spawn_neddrinkstransport_Mission",
			"Spawn_nedguns1_Mission",
			"Spawn_nedhatchback_Mission",
			"Spawn_nedhuey_Mission",
			"Spawn_nedhunter_Mission",
			"Spawn_nedifrit_Mission",
			"Spawn_nedlittlebird_Mission",
			"Spawn_nedmedical1_Mission",
			"Spawn_nedoffroad_Mission",
			"Spawn_nedresearch_Mission",
			"Spawn_nedsnipercamp_Mission",
			"Spawn_nedstrider_Mission",
			"Spawn_nedbtrader_Mission",
			"Spawn_nedural_Mission",
			"Spawn_roguenavyseals_Mission",
			"Spawn_thieves_Mission",
			"Spawn_walmart_Mission",
//			Static mission example
//			"Spawn_slums_Mission",			