R3F_LOG_CFG_disabled_by_default = false;

R3F_LOG_CFG_lock_objects_mode = "none";

R3F_LOG_CFG_unlock_objects_timer = 30;

R3F_LOG_CFG_no_gravity_objects_can_be_set_in_height_over_ground = true;

R3F_LOG_CFG_language = switch (language) do
{
	case "English":{"en"};
	case "French":{"fr"};

	default {"en"}; // If language is not supported, use English
};

R3F_LOG_CFG_string_condition_allow_logistics_on_this_client = "true";

R3F_LOG_CFG_string_condition_allow_creation_factory_on_this_client = "false";

R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
	[
			"B_APC_Wheeled_01_cannon_F",
			"B_G_Offroad_01_F",
			"B_G_Offroad_01_armed_F",
			"B_G_Offroad_01_repair_F",
			"B_G_Van_01_fuel_F",
			"B_G_Van_01_transport_F",
			"B_MRAP_01_F",
			"B_MRAP_01_gmg_F",
			"B_MRAP_01_hmg_F",
			"B_Truck_01_Repair_F",
			"B_Truck_01_ammo_F",
			"B_Truck_01_box_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_medical_F",
			"B_Truck_01_mover_F",
			"B_Truck_01_transport_F",
			"C_IDAP_Offroad_01_F",
			"C_IDAP_Offroad_02_unarmed_F",
			"C_IDAP_Truck_02_F",
			"C_IDAP_Truck_02_transport_F",
			"C_IDAP_Truck_02_water_F",
			"C_Offroad_01_F",
			"C_Offroad_01_blue_F",
			"C_Offroad_01_bluecustom_F",
			"C_Offroad_01_darkred_F",
			"C_Offroad_01_red_F",
			"C_Offroad_01_repair_F",
			"C_Offroad_01_sand_F",
			"C_Offroad_01_white_F",
			"C_Offroad_default_F",
			"C_Offroad_luxe_F",
			"C_Offroad_stripped_F",
			"Exile_Boat_SDV_CSAT",
			"Exile_Boat_SDV_Digital",
			"Exile_Boat_SDV_Grey",
			"Exile_Car_BRDM2_HQ",
			"Exile_Car_BTR40_Camo",
			"Exile_Car_BTR40_Green",
			"Exile_Car_BTR40_MG_Camo",
			"Exile_Car_BTR40_MG_Green",
			"Exile_Car_Golf_Red",
			"Exile_Car_HEMMT",
			"Exile_Car_HMMWV_M134_Green",
			"Exile_Car_HMMWV_M2_Green",
			"Exile_Car_HMMWV_MEV_Green",
			"Exile_Car_HMMWV_UNA_Green",
			"Exile_Car_Hatchback_Beige",
			"Exile_Car_Hatchback_BeigeCustom",
			"Exile_Car_Hatchback_Black",
			"Exile_Car_Hatchback_Blue",
			"Exile_Car_Hatchback_BlueCustom",
			"Exile_Car_Hatchback_Dark",
			"Exile_Car_Hatchback_Green",
			"Exile_Car_Hatchback_Grey",
			"Exile_Car_Hatchback_Rusty1",
			"Exile_Car_Hatchback_Rusty2",
			"Exile_Car_Hatchback_Rusty3",
			"Exile_Car_Hatchback_Sport_Beige",
			"Exile_Car_Hatchback_Sport_Blue",
			"Exile_Car_Hatchback_Sport_Green",
			"Exile_Car_Hatchback_Sport_Orange",
			"Exile_Car_Hatchback_Sport_Red",
			"Exile_Car_Hatchback_Sport_White",
			"Exile_Car_Hatchback_Yellow",
			"Exile_Car_Hunter",
			"Exile_Car_Ifrit",
			"Exile_Car_Ikarus_Blue",
			"Exile_Car_Lada_Green",
			"Exile_Car_Lada_Hipster",
			"Exile_Car_Lada_Red",
			"Exile_Car_Lada_Taxi",
			"Exile_Car_Lada_White",
			"Exile_Car_LandRover_Ambulance_Desert",
			"Exile_Car_LandRover_Ambulance_Green",
			"Exile_Car_LandRover_Ambulance_Sand",
			"Exile_Car_LandRover_Desert",
			"Exile_Car_LandRover_Green",
			"Exile_Car_LandRover_Red",
			"Exile_Car_LandRover_Sand",
			"Exile_Car_LandRover_Urban",
			"Exile_Car_MB4WD",
			"Exile_Car_MB4WDOpen",
			"Exile_Car_Octavius_Black",
			"Exile_Car_Octavius_White",
			"Exile_Car_Offroad_Armed_Guerilla01",
			"Exile_Car_Offroad_Armed_Guerilla02",
			"Exile_Car_Offroad_Armed_Guerilla03",
			"Exile_Car_Offroad_Armed_Guerilla04",
			"Exile_Car_Offroad_Armed_Guerilla05",
			"Exile_Car_Offroad_Armed_Guerilla06",
			"Exile_Car_Offroad_Armed_Guerilla07",
			"Exile_Car_Offroad_Armed_Guerilla08",
			"Exile_Car_Offroad_Armed_Guerilla09",
			"Exile_Car_Offroad_Armed_Guerilla10",
			"Exile_Car_Offroad_Armed_Guerilla11",
			"Exile_Car_Offroad_Armed_Guerilla12",
			"Exile_Car_Offroad_Beige",
			"Exile_Car_Offroad_Blue",
			"Exile_Car_Offroad_BlueCustom",
			"Exile_Car_Offroad_DarkRed",
			"Exile_Car_Offroad_Guerilla01",
			"Exile_Car_Offroad_Guerilla02",
			"Exile_Car_Offroad_Guerilla03",
			"Exile_Car_Offroad_Guerilla04",
			"Exile_Car_Offroad_Guerilla05",
			"Exile_Car_Offroad_Guerilla06",
			"Exile_Car_Offroad_Guerilla07",
			"Exile_Car_Offroad_Guerilla08",
			"Exile_Car_Offroad_Guerilla09",
			"Exile_Car_Offroad_Guerilla10",
			"Exile_Car_Offroad_Guerilla11",
			"Exile_Car_Offroad_Guerilla12",
			"Exile_Car_Offroad_Red",
			"Exile_Car_Offroad_Repair_Beige",
			"Exile_Car_Offroad_Repair_Blue",
			"Exile_Car_Offroad_Repair_BlueCustom",
			"Exile_Car_Offroad_Repair_Civillian",
			"Exile_Car_Offroad_Repair_DarkRed",
			"Exile_Car_Offroad_Repair_Guerilla01",
			"Exile_Car_Offroad_Repair_Guerilla02",
			"Exile_Car_Offroad_Repair_Guerilla03",
			"Exile_Car_Offroad_Repair_Guerilla04",
			"Exile_Car_Offroad_Repair_Guerilla05",
			"Exile_Car_Offroad_Repair_Guerilla06",
			"Exile_Car_Offroad_Repair_Guerilla07",
			"Exile_Car_Offroad_Repair_Guerilla08",
			"Exile_Car_Offroad_Repair_Guerilla09",
			"Exile_Car_Offroad_Repair_Guerilla10",
			"Exile_Car_Offroad_Repair_Guerilla11",
			"Exile_Car_Offroad_Repair_Guerilla12",
			"Exile_Car_Offroad_Repair_Red",
			"Exile_Car_Offroad_Repair_White",
			"Exile_Car_Offroad_Rusty1",
			"Exile_Car_Offroad_Rusty2",
			"Exile_Car_Offroad_Rusty3",
			"Exile_Car_Offroad_White",
			"Exile_Car_OldTractor_Red",
			"Exile_Car_SUVXL_Black",
			"Exile_Car_SUV_Armed_Black",
			"Exile_Car_SUV_Black",
			"Exile_Car_SUV_Grey",
			"Exile_Car_SUV_Orange",
			"Exile_Car_SUV_Red",
			"Exile_Car_SUV_Rusty1",
			"Exile_Car_SUV_Rusty2",
			"Exile_Car_SUV_Rusty3",
			"Exile_Car_Strider",
			"Exile_Car_Tempest",
			"Exile_Car_TowTractor_White",
			"Exile_Car_Tractor_Red",
			"Exile_Car_UAZ_Green",
			"Exile_Car_UAZ_Open_Green",
			"Exile_Car_Ural_Covered_Blue",
			"Exile_Car_Ural_Covered_Military",
			"Exile_Car_Ural_Covered_Worker",
			"Exile_Car_Ural_Covered_Yellow",
			"Exile_Car_Ural_Open_Blue",
			"Exile_Car_Ural_Open_Military",
			"Exile_Car_Ural_Open_Worker",
			"Exile_Car_Ural_Open_Yellow",
			"Exile_Car_V3S_Covered",
			"Exile_Car_V3S_Open",
			"Exile_Car_Van_Black",
			"Exile_Car_Van_Box_Black",
			"Exile_Car_Van_Box_Guerilla01",
			"Exile_Car_Van_Box_Guerilla02",
			"Exile_Car_Van_Box_Guerilla03",
			"Exile_Car_Van_Box_Guerilla04",
			"Exile_Car_Van_Box_Guerilla05",
			"Exile_Car_Van_Box_Guerilla06",
			"Exile_Car_Van_Box_Guerilla07",
			"Exile_Car_Van_Box_Guerilla08",
			"Exile_Car_Van_Box_Red",
			"Exile_Car_Van_Box_White",
			"Exile_Car_Van_Fuel_Black",
			"Exile_Car_Van_Fuel_Guerilla01",
			"Exile_Car_Van_Fuel_Guerilla02",
			"Exile_Car_Van_Fuel_Guerilla03",
			"Exile_Car_Van_Fuel_Red",
			"Exile_Car_Van_Fuel_White",
			"Exile_Car_Van_Guerilla01",
			"Exile_Car_Van_Guerilla02",
			"Exile_Car_Van_Guerilla03",
			"Exile_Car_Van_Guerilla04",
			"Exile_Car_Van_Guerilla05",
			"Exile_Car_Van_Guerilla06",
			"Exile_Car_Van_Guerilla07",
			"Exile_Car_Van_Guerilla08",
			"Exile_Car_Van_Red",
			"Exile_Car_Van_White",
			"Exile_Car_Volha_Black",
			"Exile_Car_Volha_Blue",
			"Exile_Car_Volha_White",
			"Exile_Car_Zamak",
			"B_LSV_01_armed_F",
			"B_LSV_01_armed_black_F",
			"B_LSV_01_armed_olive_F",
			"B_LSV_01_armed_sand_F",
			"B_T_LSV_01_armed_CTRG_F",
			"B_T_LSV_01_armed_black_F",
			"B_T_LSV_01_armed_olive_F",
			"B_T_LSV_01_armed_sand_F",
			"B_CTRG_LSV_01_light_F",
			"B_LSV_01_unarmed_F",
			"B_LSV_01_unarmed_black_F",
			"B_LSV_01_unarmed_olive_F",
			"B_LSV_01_unarmed_sand_F",
			"B_T_LSV_01_unarmed_CTRG_F",
			"B_T_LSV_01_unarmed_black_F",
			"B_T_LSV_01_unarmed_olive_F",
			"B_T_LSV_01_unarmed_sand_F",
			"O_LSV_02_armed_F",
			"O_LSV_02_armed_arid_F",
			"O_LSV_02_armed_black_F",
			"O_LSV_02_armed_ghex_F",
			"O_LSV_02_armed_viper_F",
			"O_T_LSV_02_armed_arid_F",
			"O_T_LSV_02_armed_black_F",
			"O_T_LSV_02_armed_ghex_F",
			"O_T_LSV_02_armed_viper_F",
			"O_LSV_02_unarmed_F",
			"O_LSV_02_unarmed_arid_F",
			"O_LSV_02_unarmed_black_F",
			"O_LSV_02_unarmed_ghex_F",
			"O_LSV_02_unarmed_viper_F",
			"O_T_LSV_02_unarmed_arid_F",
			"O_T_LSV_02_unarmed_black_F",
			"O_T_LSV_02_unarmed_ghex_F",
			"O_T_LSV_02_unarmed_viper_F",
			"C_Hatchback_01_F",
			"C_Hatchback_01_beigecustom_F",
			"C_Hatchback_01_black_F",
			"C_Hatchback_01_blue_F",
			"C_Hatchback_01_bluecustom_F",
			"C_Hatchback_01_dark_F",
			"C_Hatchback_01_green_F",
			"C_Hatchback_01_grey_F",
			"C_Hatchback_01_sport_F",
			"C_Hatchback_01_sport_blue_F",
			"C_Hatchback_01_sport_green_F",
			"C_Hatchback_01_sport_grey_F",
			"C_Hatchback_01_sport_orange_F",
			"C_Hatchback_01_sport_red_F",
			"C_Hatchback_01_sport_white_F",
			"C_Hatchback_01_white_F",
			"C_Hatchback_01_yellow_F",
			"C_Truck_02_box_F",
			"C_Truck_02_covered_F",
			"C_Truck_02_fuel_F",
			"C_Truck_02_transport_F",
			"C_Van_01_box_F",
			"C_Van_01_box_red_F",
			"C_Van_01_box_white_F",
			"C_Van_01_fuel_F",
			"C_Van_01_fuel_red_F",
			"C_Van_01_fuel_red_v2_F",
			"C_Van_01_fuel_white_F",
			"C_Van_01_fuel_white_v2_F",
			"C_Van_01_transport_F",
			"C_Van_01_transport_red_F",
			"C_Van_01_transport_white_F",
			"I_APC_Wheeled_03_cannon_F",
			"I_G_Offroad_01_F",
			"I_G_Offroad_01_armed_F",
			"I_G_Offroad_01_repair_F",
			"I_G_Van_01_fuel_F",
			"I_G_Van_01_transport_F",
			"I_MRAP_03_F",
			"I_MRAP_03_gmg_F",
			"I_MRAP_03_hmg_F",
			"I_Truck_02_ammo_F",
			"I_Truck_02_box_F",
			"I_Truck_02_covered_F",
			"I_Truck_02_fuel_F",
			"I_Truck_02_medical_F",
			"I_Truck_02_transport_F",
			"O_G_Offroad_01_F",
			"O_G_Offroad_01_armed_F",
			"O_G_Offroad_01_repair_F",
			"O_G_Van_01_fuel_F",
			"O_G_Van_01_transport_F",
			"O_MRAP_02_F",
			"O_MRAP_02_gmg_F",
			"O_MRAP_02_hmg_F",
			"O_T_MRAP_02_gmg_ghex_F",
			"O_T_MRAP_02_hmg_ghex_F",
			"O_Truck_02_Ammo_F",
			"O_Truck_02_box_F",
			"O_Truck_02_covered_F",
			"O_Truck_02_fuel_F",
			"O_Truck_02_medical_F",
			"O_Truck_02_transport_F",
			"O_Truck_03_ammo_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_device_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_medical_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_transport_F",
			"RHS_BTR70",
			"RHS_BTR70_MSV",
			"RHS_BTR70_VDV",
			"RHS_BTR70_VMF",
			"RHS_BTR70_VV",
			"RHS_BTR80A_MSV",
			"RHS_BTR80A_VDV",
			"RHS_BTR80A_VMF",
			"RHS_BTR80A_VV",
			"RHS_BTR80_MSV",
			"RHS_BTR80_VDV",
			"RHS_BTR80_VMF",
			"RHS_BTR80_VV",
			"RHS_M2A3",
			"RHS_M2A3_BUSKI",
			"RHS_Ural_Flat_MSV_01",
			"RHS_Ural_Flat_VDV_01",
			"RHS_Ural_Flat_VMF_01",
			"RHS_Ural_Flat_VV_01",
			"RHS_Ural_Fuel_MSV_01",
			"RHS_Ural_Fuel_VDV_01",
			"RHS_Ural_Fuel_VMF_01",
			"RHS_Ural_Fuel_VV_01",
			"RHS_Ural_MSV_01",
			"RHS_Ural_Open_Civ_01",
			"RHS_Ural_Open_Civ_02",
			"RHS_Ural_Open_Civ_03",
			"RHS_Ural_Open_Flat_MSV_01",
			"RHS_Ural_Open_Flat_VDV_01",
			"RHS_Ural_Open_Flat_VMF_01",
			"RHS_Ural_Open_Flat_VV_01",
			"RHS_Ural_Open_MSV_01",
			"RHS_Ural_Open_VDV_01",
			"RHS_Ural_Open_VMF_01",
			"RHS_Ural_Open_VV_01",
			"RHS_Ural_VDV_01",
			"RHS_Ural_VMF_01",
			"RHS_Ural_VV_01",
			"RHS_Civ_Truck_02_covered_F",
			"RHS_Civ_Truck_02_transport_F",
			"RHS_Ural_Civ_01",
			"RHS_Ural_Civ_02",
			"RHS_Ural_Civ_03",
			"RHS_Ural_Repair_MSV_01",
			"RHS_Ural_Repair_VDV_01",
			"RHS_Ural_Repair_VMF_01",
			"RHS_Ural_Repair_VV_01",
			"rhs_bmp3_late_msv",
			"rhs_bmp3mera_msv",
			"rhs_btr60_chdkz",
			"rhs_btr60_msv",
			"rhs_btr60_vdv",
			"rhs_btr60_vmf",
			"rhs_btr60_vv",
			"rhs_btr70_chdkz",
			"rhs_gaz66_ammo_vmf",
			"rhs_gaz66_flat_msv",
			"rhs_gaz66_flat_vdv",
			"rhs_gaz66_flat_vmf",
			"rhs_gaz66_flat_vv",
			"rhs_gaz66_msv",
			"rhs_gaz66_r142_msv",
			"rhs_gaz66_r142_vdv",
			"rhs_gaz66_r142_vmf",
			"rhs_gaz66_r142_vv",
			"rhs_gaz66_repair_msv",
			"rhs_gaz66_repair_vdv",
			"rhs_gaz66_repair_vmf",
			"rhs_gaz66_repair_vv",
			"rhs_gaz66_vmf",
			"rhs_gaz66_vv",
			"rhs_gaz66o_flat_msv",
			"rhs_gaz66o_flat_vdv",
			"rhs_gaz66o_flat_vmf",
			"rhs_gaz66o_flat_vv",
			"rhs_gaz66o_msv",
			"rhs_gaz66o_vdv",
			"rhs_gaz66o_vmf",
			"rhs_gaz66o_vv",
			"rhs_t72ba_tv",
			"rhs_t72bc_tv",
			"rhs_tigr_3camo_vdv",
			"rhs_tigr_ffv_3camo_vdv",
			"rhs_tigr_ffv_vdv",
			"rhs_tigr_sts_3camo_vdv",
			"rhs_tigr_vdv",
			"rhs_typhoon_vdv",
			"rhs_uaz_ags_chdkz",
			"rhs_uaz_dshkm_chdkz",
			"rhs_uaz_open_chdkz",
			"rhs_uaz_open_vmf",
			"rhs_uaz_spg9_chdkz",
			"rhs_uaz_vmf",
			"RHS_UAZ_MSV_01",
			"rhs_uaz_open_MSV_01",
			"rhs_uaz_open_vdv",
			"rhs_uaz_open_vv",
			"rhs_uaz_vdv",
			"rhs_uaz_vv",
			"rhs_kamaz5350",
			"rhs_kamaz5350_flatbed",
			"rhs_kamaz5350_flatbed_cover",
			"rhs_kamaz5350_flatbed_cover_msv",
			"rhs_kamaz5350_flatbed_cover_vdv",
			"rhs_kamaz5350_flatbed_cover_vmf",
			"rhs_kamaz5350_flatbed_cover_vv",
			"rhs_kamaz5350_flatbed_msv",
			"rhs_kamaz5350_flatbed_vdv",
			"rhs_kamaz5350_flatbed_vmf",
			"rhs_kamaz5350_flatbed_vv",
			"rhs_kamaz5350_msv",
			"rhs_kamaz5350_open",
			"rhs_kamaz5350_open_msv",
			"rhs_kamaz5350_open_vdv",
			"rhs_kamaz5350_open_vmf",
			"rhs_kamaz5350_open_vv",
			"rhs_kamaz5350_vdv",
			"rhs_kamaz5350_vmf",
			"rhs_kamaz5350_vv",
			"rhs_ural_chdkz",
			"rhs_ural_open_chdkz",
			"rhs_ural_work_chdkz",
			"rhs_ural_work_open_chdkz",
			"rhsusf_M1078A1P2_B_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_D_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_WD_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_fmtv_usarmy",
			"rhsusf_M1078A1P2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1078A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1083A1P2_B_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_fmtv_usarmy",
			"rhsusf_M1083A1P2_open_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_fmtv_usarmy",
			"rhsusf_M1084A1P2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_fmtv_usarmy",
			"rhsusf_M1084A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1084A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1085A1P2_B_D_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_WD_Medical_fmtv_usarmy",
			"rhsusf_M1232_M2_usarmy_d",
			"rhsusf_M1232_M2_usarmy_wd",
			"rhsusf_M1232_MK19_usarmy_d",
			"rhsusf_M1232_MK19_usarmy_wd",
			"rhsusf_M1232_usarmy_d",
			"rhsusf_M1232_usarmy_wd",
			"rhsusf_M1237_M2_usarmy_d",
			"rhsusf_M1237_M2_usarmy_wd",
			"rhsusf_M1237_MK19_usarmy_d",
			"rhsusf_M1237_MK19_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_wd",
			"rhsusf_M977A4_AMMO_usarmy_d",
			"rhsusf_M977A4_AMMO_usarmy_wd",
			"rhsusf_M977A4_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_BKIT_usarmy_d",
			"rhsusf_M977A4_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_usarmy_d",
			"rhsusf_M977A4_REPAIR_usarmy_wd",
			"rhsusf_M977A4_usarmy_d",
			"rhsusf_M977A4_usarmy_wd",
			"rhsusf_M978A4_BKIT_usarmy_d",
			"rhsusf_M978A4_BKIT_usarmy_wd",
			"rhsusf_M978A4_usarmy_d",
			"rhsusf_M978A4_usarmy_wd",
			"rhsusf_m1025_d",
			"rhsusf_m1025_d_Mk19",
			"rhsusf_m1025_d_m2",
			"rhsusf_m1025_d_s",
			"rhsusf_m1025_d_s_Mk19",
			"rhsusf_m1025_d_s_m2",
			"rhsusf_m1025_w",
			"rhsusf_m1025_w_m2",
			"rhsusf_m1025_w_mk19",
			"rhsusf_m1025_w_s",
			"rhsusf_m1025_w_s_Mk19",
			"rhsusf_m1025_w_s_m2",
			"rhsusf_m113_usarmy_M240",
			"rhsusf_m113_usarmy_MK19",
			"rhsusf_m113_usarmy_supply",
			"rhsusf_m113_usarmy_unarmed",
			"rhsusf_m113d_usarmy",
			"rhsusf_m113d_usarmy_M240",
			"rhsusf_m113d_usarmy_MK19",
			"rhsusf_m113d_usarmy_medical",
			"rhsusf_m113d_usarmy_supply",
			"rhsusf_m113d_usarmy_unarmed",
			"rhsusf_m1a1aimwd_usarmy",
			"rhsusf_m1a2sep1tuskiiwd_usarmy",
			"rhsusf_m998_d_2dr",
			"rhsusf_m998_d_2dr_fulltop",
			"rhsusf_m998_d_2dr_halftop",
			"rhsusf_m998_d_4dr",
			"rhsusf_m998_d_4dr_fulltop",
			"rhsusf_m998_d_4dr_halftop",
			"rhsusf_m998_d_s_2dr",
			"rhsusf_m998_d_s_2dr_fulltop",
			"rhsusf_m998_d_s_2dr_halftop",
			"rhsusf_m998_d_s_4dr",
			"rhsusf_m998_d_s_4dr_fulltop",
			"rhsusf_m998_d_s_4dr_halftop",
			"rhsusf_m998_w_2dr",
			"rhsusf_m998_w_2dr_fulltop",
			"rhsusf_m998_w_2dr_halftop",
			"rhsusf_m998_w_4dr",
			"rhsusf_m998_w_4dr_fulltop",
			"rhsusf_m998_w_4dr_halftop",
			"rhsusf_m998_w_s_2dr",
			"rhsusf_m998_w_s_2dr_fulltop",
			"rhsusf_m998_w_s_2dr_halftop",
			"rhsusf_m998_w_s_4dr",
			"rhsusf_m998_w_s_4dr_fulltop",
			"rhsusf_m998_w_s_4dr_halftop",
			"rhsusf_mrzr4_d",
			"rhsusf_mrzr4_d_mud",
			"rhsusf_mrzr4_w",
			"rhsusf_mrzr4_w_mud",
			"rhsusf_rg33_d",
			"rhsusf_rg33_m2_d",
			"rhsusf_rg33_m2_usmc_d",
			"rhsusf_rg33_m2_usmc_wd",
			"rhsusf_rg33_m2_wd",
			"rhsusf_rg33_usmc_d",
			"rhsusf_rg33_usmc_wd",
			"rhsusf_rg33_wd",
			"volha_Civ_01",
			"volha_Civ_02",
			"volha_Civ_03",
			"rhs_truck",
			"rhs_gaz66_ammo_msv",
			"rhs_gaz66_ammo_vdv",
			"rhs_gaz66_ammo_vv",
			"rhs_gaz66_ap2_msv",
			"rhs_gaz66_ap2_vdv",
			"rhs_gaz66_ap2_vmf",
			"rhs_gaz66_ap2_vv",
			"rhs_gaz66_vdv",
			"rhs_tigr_3camo_vmf",
			"rhs_tigr_3camo_vv",
			"rhs_tigr_ffv_3camo_msv",
			"rhs_tigr_ffv_3camo_vmf",
			"rhs_tigr_ffv_3camo_vv",
			"rhs_tigr_ffv_msv",
			"rhs_tigr_ffv_vmf",
			"rhs_tigr_ffv_vv",
			"rhs_tigr_m_3camo_msv",
			"rhs_tigr_m_3camo_vdv",
			"rhs_tigr_m_3camo_vmf",
			"rhs_tigr_m_3camo_vv",
			"rhs_tigr_m_msv",
			"rhs_tigr_m_vdv",
			"rhs_tigr_m_vmf",
			"rhs_tigr_m_vv",
			"rhs_tigr_msv",
			"rhs_tigr_sts_3camo_msv",
			"rhs_tigr_sts_3camo_vmf",
			"rhs_tigr_sts_3camo_vv",
			"rhs_tigr_sts_msv",
			"rhs_tigr_sts_vdv",
			"rhs_tigr_sts_vmf",
			"rhs_tigr_sts_vv",
			"rhs_tigr_vmf",
			"rhs_tigr_vv"
	];

/**
 * List of class names of objects which can be towed.
 */
R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
	[

			"B_APC_Wheeled_01_cannon_F",
			"B_G_Offroad_01_F",
			"B_G_Offroad_01_armed_F",
			"B_G_Offroad_01_repair_F",
			"B_G_Van_01_fuel_F",
			"B_G_Van_01_transport_F",
			"B_MRAP_01_F",
			"B_MRAP_01_gmg_F",
			"B_MRAP_01_hmg_F",
			"B_Truck_01_Repair_F",
			"B_Truck_01_ammo_F",
			"B_Truck_01_box_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_medical_F",
			"B_Truck_01_mover_F",
			"B_Truck_01_transport_F",
			"C_IDAP_Offroad_01_F",
			"C_IDAP_Offroad_02_unarmed_F",
			"C_IDAP_Truck_02_F",
			"C_IDAP_Truck_02_transport_F",
			"C_IDAP_Truck_02_water_F",
			"C_Offroad_01_F",
			"C_Offroad_01_blue_F",
			"C_Offroad_01_bluecustom_F",
			"C_Offroad_01_darkred_F",
			"C_Offroad_01_red_F",
			"C_Offroad_01_repair_F",
			"C_Offroad_01_sand_F",
			"C_Offroad_01_white_F",
			"C_Offroad_default_F",
			"C_Offroad_luxe_F",
			"C_Offroad_stripped_F",
			"Exile_Boat_SDV_CSAT",
			"Exile_Boat_SDV_Digital",
			"Exile_Boat_SDV_Grey",
			"Exile_Car_BRDM2_HQ",
			"Exile_Car_BTR40_Camo",
			"Exile_Car_BTR40_Green",
			"Exile_Car_BTR40_MG_Camo",
			"Exile_Car_BTR40_MG_Green",
			"Exile_Car_Golf_Red",
			"Exile_Car_HEMMT",
			"Exile_Car_HMMWV_M134_Green",
			"Exile_Car_HMMWV_M2_Green",
			"Exile_Car_HMMWV_MEV_Green",
			"Exile_Car_HMMWV_UNA_Green",
			"Exile_Car_Hatchback_Beige",
			"Exile_Car_Hatchback_BeigeCustom",
			"Exile_Car_Hatchback_Black",
			"Exile_Car_Hatchback_Blue",
			"Exile_Car_Hatchback_BlueCustom",
			"Exile_Car_Hatchback_Dark",
			"Exile_Car_Hatchback_Green",
			"Exile_Car_Hatchback_Grey",
			"Exile_Car_Hatchback_Rusty1",
			"Exile_Car_Hatchback_Rusty2",
			"Exile_Car_Hatchback_Rusty3",
			"Exile_Car_Hatchback_Sport_Beige",
			"Exile_Car_Hatchback_Sport_Blue",
			"Exile_Car_Hatchback_Sport_Green",
			"Exile_Car_Hatchback_Sport_Orange",
			"Exile_Car_Hatchback_Sport_Red",
			"Exile_Car_Hatchback_Sport_White",
			"Exile_Car_Hatchback_Yellow",
			"Exile_Car_Hunter",
			"Exile_Car_Ifrit",
			"Exile_Car_Ikarus_Blue",
			"Exile_Car_Lada_Green",
			"Exile_Car_Lada_Hipster",
			"Exile_Car_Lada_Red",
			"Exile_Car_Lada_Taxi",
			"Exile_Car_Lada_White",
			"Exile_Car_LandRover_Ambulance_Desert",
			"Exile_Car_LandRover_Ambulance_Green",
			"Exile_Car_LandRover_Ambulance_Sand",
			"Exile_Car_LandRover_Desert",
			"Exile_Car_LandRover_Green",
			"Exile_Car_LandRover_Red",
			"Exile_Car_LandRover_Sand",
			"Exile_Car_LandRover_Urban",
			"Exile_Car_MB4WD",
			"Exile_Car_MB4WDOpen",
			"Exile_Car_Octavius_Black",
			"Exile_Car_Octavius_White",
			"Exile_Car_Offroad_Armed_Guerilla01",
			"Exile_Car_Offroad_Armed_Guerilla02",
			"Exile_Car_Offroad_Armed_Guerilla03",
			"Exile_Car_Offroad_Armed_Guerilla04",
			"Exile_Car_Offroad_Armed_Guerilla05",
			"Exile_Car_Offroad_Armed_Guerilla06",
			"Exile_Car_Offroad_Armed_Guerilla07",
			"Exile_Car_Offroad_Armed_Guerilla08",
			"Exile_Car_Offroad_Armed_Guerilla09",
			"Exile_Car_Offroad_Armed_Guerilla10",
			"Exile_Car_Offroad_Armed_Guerilla11",
			"Exile_Car_Offroad_Armed_Guerilla12",
			"Exile_Car_Offroad_Beige",
			"Exile_Car_Offroad_Blue",
			"Exile_Car_Offroad_BlueCustom",
			"Exile_Car_Offroad_DarkRed",
			"Exile_Car_Offroad_Guerilla01",
			"Exile_Car_Offroad_Guerilla02",
			"Exile_Car_Offroad_Guerilla03",
			"Exile_Car_Offroad_Guerilla04",
			"Exile_Car_Offroad_Guerilla05",
			"Exile_Car_Offroad_Guerilla06",
			"Exile_Car_Offroad_Guerilla07",
			"Exile_Car_Offroad_Guerilla08",
			"Exile_Car_Offroad_Guerilla09",
			"Exile_Car_Offroad_Guerilla10",
			"Exile_Car_Offroad_Guerilla11",
			"Exile_Car_Offroad_Guerilla12",
			"Exile_Car_Offroad_Red",
			"Exile_Car_Offroad_Repair_Beige",
			"Exile_Car_Offroad_Repair_Blue",
			"Exile_Car_Offroad_Repair_BlueCustom",
			"Exile_Car_Offroad_Repair_Civillian",
			"Exile_Car_Offroad_Repair_DarkRed",
			"Exile_Car_Offroad_Repair_Guerilla01",
			"Exile_Car_Offroad_Repair_Guerilla02",
			"Exile_Car_Offroad_Repair_Guerilla03",
			"Exile_Car_Offroad_Repair_Guerilla04",
			"Exile_Car_Offroad_Repair_Guerilla05",
			"Exile_Car_Offroad_Repair_Guerilla06",
			"Exile_Car_Offroad_Repair_Guerilla07",
			"Exile_Car_Offroad_Repair_Guerilla08",
			"Exile_Car_Offroad_Repair_Guerilla09",
			"Exile_Car_Offroad_Repair_Guerilla10",
			"Exile_Car_Offroad_Repair_Guerilla11",
			"Exile_Car_Offroad_Repair_Guerilla12",
			"Exile_Car_Offroad_Repair_Red",
			"Exile_Car_Offroad_Repair_White",
			"Exile_Car_Offroad_Rusty1",
			"Exile_Car_Offroad_Rusty2",
			"Exile_Car_Offroad_Rusty3",
			"Exile_Car_Offroad_White",
			"Exile_Car_OldTractor_Red",
			"Exile_Car_SUVXL_Black",
			"Exile_Car_SUV_Armed_Black",
			"Exile_Car_SUV_Black",
			"Exile_Car_SUV_Grey",
			"Exile_Car_SUV_Orange",
			"Exile_Car_SUV_Red",
			"Exile_Car_SUV_Rusty1",
			"Exile_Car_SUV_Rusty2",
			"Exile_Car_SUV_Rusty3",
			"Exile_Car_Strider",
			"Exile_Car_Tempest",
			"Exile_Car_TowTractor_White",
			"Exile_Car_Tractor_Red",
			"Exile_Car_UAZ_Green",
			"Exile_Car_UAZ_Open_Green",
			"Exile_Car_Ural_Covered_Blue",
			"Exile_Car_Ural_Covered_Military",
			"Exile_Car_Ural_Covered_Worker",
			"Exile_Car_Ural_Covered_Yellow",
			"Exile_Car_Ural_Open_Blue",
			"Exile_Car_Ural_Open_Military",
			"Exile_Car_Ural_Open_Worker",
			"Exile_Car_Ural_Open_Yellow",
			"Exile_Car_V3S_Covered",
			"Exile_Car_V3S_Open",
			"Exile_Car_Van_Black",
			"Exile_Car_Van_Box_Black",
			"Exile_Car_Van_Box_Guerilla01",
			"Exile_Car_Van_Box_Guerilla02",
			"Exile_Car_Van_Box_Guerilla03",
			"Exile_Car_Van_Box_Guerilla04",
			"Exile_Car_Van_Box_Guerilla05",
			"Exile_Car_Van_Box_Guerilla06",
			"Exile_Car_Van_Box_Guerilla07",
			"Exile_Car_Van_Box_Guerilla08",
			"Exile_Car_Van_Box_Red",
			"Exile_Car_Van_Box_White",
			"Exile_Car_Van_Fuel_Black",
			"Exile_Car_Van_Fuel_Guerilla01",
			"Exile_Car_Van_Fuel_Guerilla02",
			"Exile_Car_Van_Fuel_Guerilla03",
			"Exile_Car_Van_Fuel_Red",
			"Exile_Car_Van_Fuel_White",
			"Exile_Car_Van_Guerilla01",
			"Exile_Car_Van_Guerilla02",
			"Exile_Car_Van_Guerilla03",
			"Exile_Car_Van_Guerilla04",
			"Exile_Car_Van_Guerilla05",
			"Exile_Car_Van_Guerilla06",
			"Exile_Car_Van_Guerilla07",
			"Exile_Car_Van_Guerilla08",
			"Exile_Car_Van_Red",
			"Exile_Car_Van_White",
			"Exile_Car_Volha_Black",
			"Exile_Car_Volha_Blue",
			"Exile_Car_Volha_White",
			"Exile_Car_Zamak",
			"B_LSV_01_armed_F",
			"B_LSV_01_armed_black_F",
			"B_LSV_01_armed_olive_F",
			"B_LSV_01_armed_sand_F",
			"B_T_LSV_01_armed_CTRG_F",
			"B_T_LSV_01_armed_black_F",
			"B_T_LSV_01_armed_olive_F",
			"B_T_LSV_01_armed_sand_F",
			"B_CTRG_LSV_01_light_F",
			"B_LSV_01_unarmed_F",
			"B_LSV_01_unarmed_black_F",
			"B_LSV_01_unarmed_olive_F",
			"B_LSV_01_unarmed_sand_F",
			"B_T_LSV_01_unarmed_CTRG_F",
			"B_T_LSV_01_unarmed_black_F",
			"B_T_LSV_01_unarmed_olive_F",
			"B_T_LSV_01_unarmed_sand_F",
			"O_LSV_02_armed_F",
			"O_LSV_02_armed_arid_F",
			"O_LSV_02_armed_black_F",
			"O_LSV_02_armed_ghex_F",
			"O_LSV_02_armed_viper_F",
			"O_T_LSV_02_armed_arid_F",
			"O_T_LSV_02_armed_black_F",
			"O_T_LSV_02_armed_ghex_F",
			"O_T_LSV_02_armed_viper_F",
			"O_LSV_02_unarmed_F",
			"O_LSV_02_unarmed_arid_F",
			"O_LSV_02_unarmed_black_F",
			"O_LSV_02_unarmed_ghex_F",
			"O_LSV_02_unarmed_viper_F",
			"O_T_LSV_02_unarmed_arid_F",
			"O_T_LSV_02_unarmed_black_F",
			"O_T_LSV_02_unarmed_ghex_F",
			"O_T_LSV_02_unarmed_viper_F",
			"C_Hatchback_01_F",
			"C_Hatchback_01_beigecustom_F",
			"C_Hatchback_01_black_F",
			"C_Hatchback_01_blue_F",
			"C_Hatchback_01_bluecustom_F",
			"C_Hatchback_01_dark_F",
			"C_Hatchback_01_green_F",
			"C_Hatchback_01_grey_F",
			"C_Hatchback_01_sport_F",
			"C_Hatchback_01_sport_blue_F",
			"C_Hatchback_01_sport_green_F",
			"C_Hatchback_01_sport_grey_F",
			"C_Hatchback_01_sport_orange_F",
			"C_Hatchback_01_sport_red_F",
			"C_Hatchback_01_sport_white_F",
			"C_Hatchback_01_white_F",
			"C_Hatchback_01_yellow_F",
			"C_Truck_02_box_F",
			"C_Truck_02_covered_F",
			"C_Truck_02_fuel_F",
			"C_Truck_02_transport_F",
			"C_Van_01_box_F",
			"C_Van_01_box_red_F",
			"C_Van_01_box_white_F",
			"C_Van_01_fuel_F",
			"C_Van_01_fuel_red_F",
			"C_Van_01_fuel_red_v2_F",
			"C_Van_01_fuel_white_F",
			"C_Van_01_fuel_white_v2_F",
			"C_Van_01_transport_F",
			"C_Van_01_transport_red_F",
			"C_Van_01_transport_white_F",
			"I_APC_Wheeled_03_cannon_F",
			"I_G_Offroad_01_F",
			"I_G_Offroad_01_armed_F",
			"I_G_Offroad_01_repair_F",
			"I_G_Van_01_fuel_F",
			"I_G_Van_01_transport_F",
			"I_MRAP_03_F",
			"I_MRAP_03_gmg_F",
			"I_MRAP_03_hmg_F",
			"I_Truck_02_ammo_F",
			"I_Truck_02_box_F",
			"I_Truck_02_covered_F",
			"I_Truck_02_fuel_F",
			"I_Truck_02_medical_F",
			"I_Truck_02_transport_F",
			"O_G_Offroad_01_F",
			"O_G_Offroad_01_armed_F",
			"O_G_Offroad_01_repair_F",
			"O_G_Van_01_fuel_F",
			"O_G_Van_01_transport_F",
			"O_MRAP_02_F",
			"O_MRAP_02_gmg_F",
			"O_MRAP_02_hmg_F",
			"O_T_MRAP_02_gmg_ghex_F",
			"O_T_MRAP_02_hmg_ghex_F",
			"O_Truck_02_Ammo_F",
			"O_Truck_02_box_F",
			"O_Truck_02_covered_F",
			"O_Truck_02_fuel_F",
			"O_Truck_02_medical_F",
			"O_Truck_02_transport_F",
			"O_Truck_03_ammo_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_device_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_medical_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_transport_F",
			"RHS_BTR70",
			"RHS_BTR70_MSV",
			"RHS_BTR70_VDV",
			"RHS_BTR70_VMF",
			"RHS_BTR70_VV",
			"RHS_BTR80A_MSV",
			"RHS_BTR80A_VDV",
			"RHS_BTR80A_VMF",
			"RHS_BTR80A_VV",
			"RHS_BTR80_MSV",
			"RHS_BTR80_VDV",
			"RHS_BTR80_VMF",
			"RHS_BTR80_VV",
			"RHS_M2A3",
			"RHS_M2A3_BUSKI",
			"RHS_Ural_Flat_MSV_01",
			"RHS_Ural_Flat_VDV_01",
			"RHS_Ural_Flat_VMF_01",
			"RHS_Ural_Flat_VV_01",
			"RHS_Ural_Fuel_MSV_01",
			"RHS_Ural_Fuel_VDV_01",
			"RHS_Ural_Fuel_VMF_01",
			"RHS_Ural_Fuel_VV_01",
			"RHS_Ural_MSV_01",
			"RHS_Ural_Open_Civ_01",
			"RHS_Ural_Open_Civ_02",
			"RHS_Ural_Open_Civ_03",
			"RHS_Ural_Open_Flat_MSV_01",
			"RHS_Ural_Open_Flat_VDV_01",
			"RHS_Ural_Open_Flat_VMF_01",
			"RHS_Ural_Open_Flat_VV_01",
			"RHS_Ural_Open_MSV_01",
			"RHS_Ural_Open_VDV_01",
			"RHS_Ural_Open_VMF_01",
			"RHS_Ural_Open_VV_01",
			"RHS_Ural_VDV_01",
			"RHS_Ural_VMF_01",
			"RHS_Ural_VV_01",
			"RHS_Civ_Truck_02_covered_F",
			"RHS_Civ_Truck_02_transport_F",
			"RHS_Ural_Civ_01",
			"RHS_Ural_Civ_02",
			"RHS_Ural_Civ_03",
			"RHS_Ural_Repair_MSV_01",
			"RHS_Ural_Repair_VDV_01",
			"RHS_Ural_Repair_VMF_01",
			"RHS_Ural_Repair_VV_01",
			"rhs_bmp3_late_msv",
			"rhs_bmp3mera_msv",
			"rhs_btr60_chdkz",
			"rhs_btr60_msv",
			"rhs_btr60_vdv",
			"rhs_btr60_vmf",
			"rhs_btr60_vv",
			"rhs_btr70_chdkz",
			"rhs_gaz66_ammo_vmf",
			"rhs_gaz66_flat_msv",
			"rhs_gaz66_flat_vdv",
			"rhs_gaz66_flat_vmf",
			"rhs_gaz66_flat_vv",
			"rhs_gaz66_msv",
			"rhs_gaz66_r142_msv",
			"rhs_gaz66_r142_vdv",
			"rhs_gaz66_r142_vmf",
			"rhs_gaz66_r142_vv",
			"rhs_gaz66_repair_msv",
			"rhs_gaz66_repair_vdv",
			"rhs_gaz66_repair_vmf",
			"rhs_gaz66_repair_vv",
			"rhs_gaz66_vmf",
			"rhs_gaz66_vv",
			"rhs_gaz66o_flat_msv",
			"rhs_gaz66o_flat_vdv",
			"rhs_gaz66o_flat_vmf",
			"rhs_gaz66o_flat_vv",
			"rhs_gaz66o_msv",
			"rhs_gaz66o_vdv",
			"rhs_gaz66o_vmf",
			"rhs_gaz66o_vv",
			"rhs_t72ba_tv",
			"rhs_t72bc_tv",
			"rhs_tigr_3camo_vdv",
			"rhs_tigr_ffv_3camo_vdv",
			"rhs_tigr_ffv_vdv",
			"rhs_tigr_sts_3camo_vdv",
			"rhs_tigr_vdv",
			"rhs_typhoon_vdv",
			"rhs_uaz_ags_chdkz",
			"rhs_uaz_dshkm_chdkz",
			"rhs_uaz_open_chdkz",
			"rhs_uaz_open_vmf",
			"rhs_uaz_spg9_chdkz",
			"rhs_uaz_vmf",
			"RHS_UAZ_MSV_01",
			"rhs_uaz_open_MSV_01",
			"rhs_uaz_open_vdv",
			"rhs_uaz_open_vv",
			"rhs_uaz_vdv",
			"rhs_uaz_vv",
			"rhs_kamaz5350",
			"rhs_kamaz5350_flatbed",
			"rhs_kamaz5350_flatbed_cover",
			"rhs_kamaz5350_flatbed_cover_msv",
			"rhs_kamaz5350_flatbed_cover_vdv",
			"rhs_kamaz5350_flatbed_cover_vmf",
			"rhs_kamaz5350_flatbed_cover_vv",
			"rhs_kamaz5350_flatbed_msv",
			"rhs_kamaz5350_flatbed_vdv",
			"rhs_kamaz5350_flatbed_vmf",
			"rhs_kamaz5350_flatbed_vv",
			"rhs_kamaz5350_msv",
			"rhs_kamaz5350_open",
			"rhs_kamaz5350_open_msv",
			"rhs_kamaz5350_open_vdv",
			"rhs_kamaz5350_open_vmf",
			"rhs_kamaz5350_open_vv",
			"rhs_kamaz5350_vdv",
			"rhs_kamaz5350_vmf",
			"rhs_kamaz5350_vv",
			"rhs_ural_chdkz",
			"rhs_ural_open_chdkz",
			"rhs_ural_work_chdkz",
			"rhs_ural_work_open_chdkz",
			"rhsusf_M1078A1P2_B_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_D_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_WD_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_fmtv_usarmy",
			"rhsusf_M1078A1P2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1078A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1083A1P2_B_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_fmtv_usarmy",
			"rhsusf_M1083A1P2_open_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_fmtv_usarmy",
			"rhsusf_M1084A1P2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_fmtv_usarmy",
			"rhsusf_M1084A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1084A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1085A1P2_B_D_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_WD_Medical_fmtv_usarmy",
			"rhsusf_M1232_M2_usarmy_d",
			"rhsusf_M1232_M2_usarmy_wd",
			"rhsusf_M1232_MK19_usarmy_d",
			"rhsusf_M1232_MK19_usarmy_wd",
			"rhsusf_M1232_usarmy_d",
			"rhsusf_M1232_usarmy_wd",
			"rhsusf_M1237_M2_usarmy_d",
			"rhsusf_M1237_M2_usarmy_wd",
			"rhsusf_M1237_MK19_usarmy_d",
			"rhsusf_M1237_MK19_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_wd",
			"rhsusf_M977A4_AMMO_usarmy_d",
			"rhsusf_M977A4_AMMO_usarmy_wd",
			"rhsusf_M977A4_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_BKIT_usarmy_d",
			"rhsusf_M977A4_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_usarmy_d",
			"rhsusf_M977A4_REPAIR_usarmy_wd",
			"rhsusf_M977A4_usarmy_d",
			"rhsusf_M977A4_usarmy_wd",
			"rhsusf_M978A4_BKIT_usarmy_d",
			"rhsusf_M978A4_BKIT_usarmy_wd",
			"rhsusf_M978A4_usarmy_d",
			"rhsusf_M978A4_usarmy_wd",
			"rhsusf_m1025_d",
			"rhsusf_m1025_d_Mk19",
			"rhsusf_m1025_d_m2",
			"rhsusf_m1025_d_s",
			"rhsusf_m1025_d_s_Mk19",
			"rhsusf_m1025_d_s_m2",
			"rhsusf_m1025_w",
			"rhsusf_m1025_w_m2",
			"rhsusf_m1025_w_mk19",
			"rhsusf_m1025_w_s",
			"rhsusf_m1025_w_s_Mk19",
			"rhsusf_m1025_w_s_m2",
			"rhsusf_m113_usarmy_M240",
			"rhsusf_m113_usarmy_MK19",
			"rhsusf_m113_usarmy_supply",
			"rhsusf_m113_usarmy_unarmed",
			"rhsusf_m113d_usarmy",
			"rhsusf_m113d_usarmy_M240",
			"rhsusf_m113d_usarmy_MK19",
			"rhsusf_m113d_usarmy_medical",
			"rhsusf_m113d_usarmy_supply",
			"rhsusf_m113d_usarmy_unarmed",
			"rhsusf_m1a1aimwd_usarmy",
			"rhsusf_m1a2sep1tuskiiwd_usarmy",
			"rhsusf_m998_d_2dr",
			"rhsusf_m998_d_2dr_fulltop",
			"rhsusf_m998_d_2dr_halftop",
			"rhsusf_m998_d_4dr",
			"rhsusf_m998_d_4dr_fulltop",
			"rhsusf_m998_d_4dr_halftop",
			"rhsusf_m998_d_s_2dr",
			"rhsusf_m998_d_s_2dr_fulltop",
			"rhsusf_m998_d_s_2dr_halftop",
			"rhsusf_m998_d_s_4dr",
			"rhsusf_m998_d_s_4dr_fulltop",
			"rhsusf_m998_d_s_4dr_halftop",
			"rhsusf_m998_w_2dr",
			"rhsusf_m998_w_2dr_fulltop",
			"rhsusf_m998_w_2dr_halftop",
			"rhsusf_m998_w_4dr",
			"rhsusf_m998_w_4dr_fulltop",
			"rhsusf_m998_w_4dr_halftop",
			"rhsusf_m998_w_s_2dr",
			"rhsusf_m998_w_s_2dr_fulltop",
			"rhsusf_m998_w_s_2dr_halftop",
			"rhsusf_m998_w_s_4dr",
			"rhsusf_m998_w_s_4dr_fulltop",
			"rhsusf_m998_w_s_4dr_halftop",
			"rhsusf_mrzr4_d",
			"rhsusf_mrzr4_d_mud",
			"rhsusf_mrzr4_w",
			"rhsusf_mrzr4_w_mud",
			"rhsusf_rg33_d",
			"rhsusf_rg33_m2_d",
			"rhsusf_rg33_m2_usmc_d",
			"rhsusf_rg33_m2_usmc_wd",
			"rhsusf_rg33_m2_wd",
			"rhsusf_rg33_usmc_d",
			"rhsusf_rg33_usmc_wd",
			"rhsusf_rg33_wd",
			"volha_Civ_01",
			"volha_Civ_02",
			"volha_Civ_03",
			"rhs_truck",
			"rhs_gaz66_ammo_msv",
			"rhs_gaz66_ammo_vdv",
			"rhs_gaz66_ammo_vv",
			"rhs_gaz66_ap2_msv",
			"rhs_gaz66_ap2_vdv",
			"rhs_gaz66_ap2_vmf",
			"rhs_gaz66_ap2_vv",
			"rhs_gaz66_vdv",
			"rhs_tigr_3camo_vmf",
			"rhs_tigr_3camo_vv",
			"rhs_tigr_ffv_3camo_msv",
			"rhs_tigr_ffv_3camo_vmf",
			"rhs_tigr_ffv_3camo_vv",
			"rhs_tigr_ffv_msv",
			"rhs_tigr_ffv_vmf",
			"rhs_tigr_ffv_vv",
			"rhs_tigr_m_3camo_msv",
			"rhs_tigr_m_3camo_vdv",
			"rhs_tigr_m_3camo_vmf",
			"rhs_tigr_m_3camo_vv",
			"rhs_tigr_m_msv",
			"rhs_tigr_m_vdv",
			"rhs_tigr_m_vmf",
			"rhs_tigr_m_vv",
			"rhs_tigr_msv",
			"rhs_tigr_sts_3camo_msv",
			"rhs_tigr_sts_3camo_vmf",
			"rhs_tigr_sts_3camo_vv",
			"rhs_tigr_sts_msv",
			"rhs_tigr_sts_vdv",
			"rhs_tigr_sts_vmf",
			"rhs_tigr_sts_vv",
			"rhs_tigr_vmf",
			"rhs_tigr_vv"
	];

/**
 * List of class names of helicopters which can lift objects.
 */
R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
	[
			"B_Heli_Attack_01_F",
			"B_Heli_Attack_01_dynamicLoadout_F",
			"B_Heli_Light_01_F",
			"B_Heli_Light_01_armed_F",
			"B_Heli_Light_01_dynamicLoadout_F",
			"B_Heli_Light_01_stripped_F",
			"B_Heli_Transport_01_F",
			"B_Heli_Transport_01_camo_F",
			"B_Heli_Transport_03_F",
			"B_Heli_Transport_03_black_F",
			"B_Heli_Transport_03_unarmed_F",
			"B_Heli_Transport_03_unarmed_green_F",
			"C_Heli_Light_01_civil_F",
			"C_Heli_light_01_blueLine_F",
			"C_Heli_light_01_blue_F",
			"C_Heli_light_01_digital_F",
			"C_Heli_light_01_elliptical_F",
			"C_Heli_light_01_furious_F",
			"C_Heli_light_01_graywatcher_F",
			"C_Heli_light_01_ion_F",
			"C_Heli_light_01_jeans_F",
			"C_Heli_light_01_light_F",
			"C_Heli_light_01_luxe_F",
			"C_Heli_light_01_red_F",
			"C_Heli_light_01_shadow_F",
			"C_Heli_light_01_sheriff_F",
			"C_Heli_light_01_speedy_F",
			"C_Heli_light_01_stripped_F",
			"C_Heli_light_01_sunset_F",
			"C_Heli_light_01_vrana_F",
			"C_Heli_light_01_wasp_F",
			"C_Heli_light_01_wave_F",
			"Exile_Chopper_Hellcat_Green",
			"Exile_Chopper_Huey_Armed_Green",
			"Exile_Chopper_Huey_Green",
			"Exile_Chopper_Hummingbird_Civillian_Wasp",
			"Exile_Chopper_Hummingbird_Green",
			"Exile_Chopper_Huron_Black",
			"Exile_Chopper_Mohawk_FIA",
			"Exile_Chopper_Orca_BlackCustom",
			"Exile_Chopper_Taru_Black",
			"Exile_Chopper_Taru_Covered_Black",
			"Exile_Chopper_Taru_Transport_Black",
			"I_Heli_Transport_02_F",
			"I_Heli_light_03_F",
			"I_Heli_light_03_dynamicLoadout_F",
			"I_Heli_light_03_unarmed_F",
			"O_Heli_Attack_02_F",
			"O_Heli_Attack_02_black_F",
			"O_Heli_Attack_02_dynamicLoadout_F",
			"O_Heli_Attack_02_dynamicLoadout_black_F",
			"O_Heli_Light_02_F",
			"O_Heli_Light_02_dynamicLoadout_F",
			"O_Heli_Light_02_unarmed_F",
			"O_Heli_Light_02_v2_F",
			"O_Heli_Transport_04_F",
			"O_Heli_Transport_04_ammo_F",
			"O_Heli_Transport_04_ammo_black_F",
			"O_Heli_Transport_04_bench_F",
			"O_Heli_Transport_04_bench_black_F",
			"O_Heli_Transport_04_black_F",
			"O_Heli_Transport_04_box_F",
			"O_Heli_Transport_04_box_black_F",
			"O_Heli_Transport_04_covered_F",
			"O_Heli_Transport_04_covered_black_F",
			"O_Heli_Transport_04_fuel_F",
			"O_Heli_Transport_04_fuel_black_F",
			"O_Heli_Transport_04_medevac_F",
			"O_Heli_Transport_04_medevac_black_F",
			"O_Heli_Transport_04_repair_F",
			"O_Heli_Transport_04_repair_black_F",
			"RHS_AH1Z",
			"RHS_AH1Z_CS",
			"RHS_AH1Z_GS",
			"RHS_AH1Z_wd",
			"RHS_AH1Z_wd_CS",
			"RHS_AH1Z_wd_GS",
			"RHS_AH64D",
			"RHS_AH64DGrey",
			"RHS_AH64D_AA",
			"RHS_AH64D_CS",
			"RHS_AH64D_GS",
			"RHS_AH64D_wd",
			"RHS_AH64D_wd_AA",
			"RHS_AH64D_wd_CS",
			"RHS_AH64D_wd_GS",
			"RHS_CH_47F",
			"RHS_CH_47F_10",
			"RHS_CH_47F_light",
			"RHS_Ka52_UPK23_vvs",
			"RHS_Ka52_UPK23_vvsc",
			"RHS_Ka52_vvs",
			"RHS_Ka52_vvsc",
			"RHS_MELB_AH6M",
			"RHS_MELB_AH6M_H",
			"RHS_MELB_AH6M_M",
			"RHS_MELB_H6M",
			"RHS_MELB_MH6M",
			"RHS_MI8MTV3_UPK23_vvs",
			"RHS_MI8MTV3_UPK23_vvsc",
			"RHS_MI8MTV3_vvs",
			"RHS_MI8MTV3_vvsc",
			"RHS_Mi24P_AT_vdv",
			"RHS_Mi24P_AT_vvs",
			"RHS_Mi24P_AT_vvsc",
			"RHS_Mi24P_CAS_vdv",
			"RHS_Mi24P_CAS_vvs",
			"RHS_Mi24P_CAS_vvsc",
			"RHS_Mi24P_vdv",
			"RHS_Mi24P_vvs",
			"RHS_Mi24P_vvsc",
			"RHS_Mi24V_AT_vvs",
			"RHS_Mi24V_AT_vvsc",
			"RHS_Mi24V_FAB_vdv",
			"RHS_Mi24V_FAB_vvs",
			"RHS_Mi24V_FAB_vvsc",
			"RHS_Mi24V_UPK23_vdv",
			"RHS_Mi24V_UPK23_vvs",
			"RHS_Mi24V_UPK23_vvsc",
			"RHS_Mi24V_vdv",
			"RHS_Mi24V_vvs",
			"RHS_Mi24V_vvsc",
			"RHS_Mi24Vt_vvs",
			"RHS_Mi8AMTSh_FAB_vvs",
			"RHS_Mi8AMTSh_FAB_vvsc",
			"RHS_Mi8AMTSh_UPK23_vvs",
			"RHS_Mi8AMTSh_UPK23_vvsc",
			"RHS_Mi8AMTSh_vvs",
			"RHS_Mi8AMTSh_vvsc",
			"RHS_Mi8AMT_vdv",
			"RHS_Mi8AMT_vvs",
			"RHS_Mi8AMT_vvsc",
			"RHS_Mi8MTV3_FAB_vdv",
			"RHS_Mi8MTV3_FAB_vvs",
			"RHS_Mi8MTV3_FAB_vvsc",
			"RHS_Mi8MTV3_UPK23_vdv",
			"RHS_Mi8MTV3_vdv",
			"RHS_Mi8amt_civilian",
			"RHS_Mi8mt_Cargo_vdv",
			"RHS_Mi8mt_Cargo_vv",
			"RHS_Mi8mt_Cargo_vvsc",
			"RHS_Mi8mt_vdv",
			"RHS_Mi8mt_vv",
			"RHS_Mi8mt_vvs",
			"RHS_Mi8mt_vvsc",
			"RHS_Mi24Vt_vvsc",
			"RHS_Mi8MTV3_heavy_vdv",
			"RHS_Mi8MTV3_heavy_vvs",
			"RHS_Mi8MTV3_heavy_vvsc",
			"RHS_Mi8mtv3_Cargo_vdv",
			"RHS_Mi8mtv3_Cargo_vvs",
			"RHS_Mi8mtv3_Cargo_vvsc",
			"RHS_UH1Y",
			"RHS_UH1Y_FFAR",
			"RHS_UH1Y_FFAR_d",
			"RHS_UH1Y_UNARMED_d",
			"RHS_UH1Y_d",
			"RHS_UH60M",
			"RHS_UH60M_MEV",
			"RHS_UH60M_MEV2",
			"RHS_UH60M_MEV_d",
			"RHS_UH60M_d",
			"rhs_Mi8mt_cargo_vvs",
			"rhs_UH1Y_unarmed",
			"rhs_UH60M_MEV2_d",
			"rhs_ka60_c",
			"rhs_ka60_grey",
			"rhs_mi28n_s13_vvs",
			"rhs_mi28n_s13_vvsc",
			"rhs_mi28n_vvs",
			"rhs_mi28n_vvsc",
			"rhsusf_CH53E_USMC",
			"rhsusf_CH53E_USMC_D"
	];

/**
 * List of class names of objects which can be lifted.
 */
R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
	[
			"B_APC_Wheeled_01_cannon_F",
			"B_G_Offroad_01_F",
			"B_G_Offroad_01_armed_F",
			"B_G_Offroad_01_repair_F",
			"B_G_Van_01_fuel_F",
			"B_G_Van_01_transport_F",
			"B_MRAP_01_F",
			"B_MRAP_01_gmg_F",
			"B_MRAP_01_hmg_F",
			"B_Truck_01_Repair_F",
			"B_Truck_01_ammo_F",
			"B_Truck_01_box_F",
			"B_Truck_01_covered_F",
			"B_Truck_01_fuel_F",
			"B_Truck_01_medical_F",
			"B_Truck_01_mover_F",
			"B_Truck_01_transport_F",
			"C_IDAP_Offroad_01_F",
			"C_IDAP_Offroad_02_unarmed_F",
			"C_IDAP_Truck_02_F",
			"C_IDAP_Truck_02_transport_F",
			"C_IDAP_Truck_02_water_F",
			"C_Offroad_01_F",
			"C_Offroad_01_blue_F",
			"C_Offroad_01_bluecustom_F",
			"C_Offroad_01_darkred_F",
			"C_Offroad_01_red_F",
			"C_Offroad_01_repair_F",
			"C_Offroad_01_sand_F",
			"C_Offroad_01_white_F",
			"C_Offroad_default_F",
			"C_Offroad_luxe_F",
			"C_Offroad_stripped_F",
			"Exile_Boat_SDV_CSAT",
			"Exile_Boat_SDV_Digital",
			"Exile_Boat_SDV_Grey",
			"Exile_Car_BRDM2_HQ",
			"Exile_Car_BTR40_Camo",
			"Exile_Car_BTR40_Green",
			"Exile_Car_BTR40_MG_Camo",
			"Exile_Car_BTR40_MG_Green",
			"Exile_Car_Golf_Red",
			"Exile_Car_HEMMT",
			"Exile_Car_HMMWV_M134_Green",
			"Exile_Car_HMMWV_M2_Green",
			"Exile_Car_HMMWV_MEV_Green",
			"Exile_Car_HMMWV_UNA_Green",
			"Exile_Car_Hatchback_Beige",
			"Exile_Car_Hatchback_BeigeCustom",
			"Exile_Car_Hatchback_Black",
			"Exile_Car_Hatchback_Blue",
			"Exile_Car_Hatchback_BlueCustom",
			"Exile_Car_Hatchback_Dark",
			"Exile_Car_Hatchback_Green",
			"Exile_Car_Hatchback_Grey",
			"Exile_Car_Hatchback_Rusty1",
			"Exile_Car_Hatchback_Rusty2",
			"Exile_Car_Hatchback_Rusty3",
			"Exile_Car_Hatchback_Sport_Beige",
			"Exile_Car_Hatchback_Sport_Blue",
			"Exile_Car_Hatchback_Sport_Green",
			"Exile_Car_Hatchback_Sport_Orange",
			"Exile_Car_Hatchback_Sport_Red",
			"Exile_Car_Hatchback_Sport_White",
			"Exile_Car_Hatchback_Yellow",
			"Exile_Car_Hunter",
			"Exile_Car_Ifrit",
			"Exile_Car_Ikarus_Blue",
			"Exile_Car_Lada_Green",
			"Exile_Car_Lada_Hipster",
			"Exile_Car_Lada_Red",
			"Exile_Car_Lada_Taxi",
			"Exile_Car_Lada_White",
			"Exile_Car_LandRover_Ambulance_Desert",
			"Exile_Car_LandRover_Ambulance_Green",
			"Exile_Car_LandRover_Ambulance_Sand",
			"Exile_Car_LandRover_Desert",
			"Exile_Car_LandRover_Green",
			"Exile_Car_LandRover_Red",
			"Exile_Car_LandRover_Sand",
			"Exile_Car_LandRover_Urban",
			"Exile_Car_MB4WD",
			"Exile_Car_MB4WDOpen",
			"Exile_Car_Octavius_Black",
			"Exile_Car_Octavius_White",
			"Exile_Car_Offroad_Armed_Guerilla01",
			"Exile_Car_Offroad_Armed_Guerilla02",
			"Exile_Car_Offroad_Armed_Guerilla03",
			"Exile_Car_Offroad_Armed_Guerilla04",
			"Exile_Car_Offroad_Armed_Guerilla05",
			"Exile_Car_Offroad_Armed_Guerilla06",
			"Exile_Car_Offroad_Armed_Guerilla07",
			"Exile_Car_Offroad_Armed_Guerilla08",
			"Exile_Car_Offroad_Armed_Guerilla09",
			"Exile_Car_Offroad_Armed_Guerilla10",
			"Exile_Car_Offroad_Armed_Guerilla11",
			"Exile_Car_Offroad_Armed_Guerilla12",
			"Exile_Car_Offroad_Beige",
			"Exile_Car_Offroad_Blue",
			"Exile_Car_Offroad_BlueCustom",
			"Exile_Car_Offroad_DarkRed",
			"Exile_Car_Offroad_Guerilla01",
			"Exile_Car_Offroad_Guerilla02",
			"Exile_Car_Offroad_Guerilla03",
			"Exile_Car_Offroad_Guerilla04",
			"Exile_Car_Offroad_Guerilla05",
			"Exile_Car_Offroad_Guerilla06",
			"Exile_Car_Offroad_Guerilla07",
			"Exile_Car_Offroad_Guerilla08",
			"Exile_Car_Offroad_Guerilla09",
			"Exile_Car_Offroad_Guerilla10",
			"Exile_Car_Offroad_Guerilla11",
			"Exile_Car_Offroad_Guerilla12",
			"Exile_Car_Offroad_Red",
			"Exile_Car_Offroad_Repair_Beige",
			"Exile_Car_Offroad_Repair_Blue",
			"Exile_Car_Offroad_Repair_BlueCustom",
			"Exile_Car_Offroad_Repair_Civillian",
			"Exile_Car_Offroad_Repair_DarkRed",
			"Exile_Car_Offroad_Repair_Guerilla01",
			"Exile_Car_Offroad_Repair_Guerilla02",
			"Exile_Car_Offroad_Repair_Guerilla03",
			"Exile_Car_Offroad_Repair_Guerilla04",
			"Exile_Car_Offroad_Repair_Guerilla05",
			"Exile_Car_Offroad_Repair_Guerilla06",
			"Exile_Car_Offroad_Repair_Guerilla07",
			"Exile_Car_Offroad_Repair_Guerilla08",
			"Exile_Car_Offroad_Repair_Guerilla09",
			"Exile_Car_Offroad_Repair_Guerilla10",
			"Exile_Car_Offroad_Repair_Guerilla11",
			"Exile_Car_Offroad_Repair_Guerilla12",
			"Exile_Car_Offroad_Repair_Red",
			"Exile_Car_Offroad_Repair_White",
			"Exile_Car_Offroad_Rusty1",
			"Exile_Car_Offroad_Rusty2",
			"Exile_Car_Offroad_Rusty3",
			"Exile_Car_Offroad_White",
			"Exile_Car_OldTractor_Red",
			"Exile_Car_SUVXL_Black",
			"Exile_Car_SUV_Armed_Black",
			"Exile_Car_SUV_Black",
			"Exile_Car_SUV_Grey",
			"Exile_Car_SUV_Orange",
			"Exile_Car_SUV_Red",
			"Exile_Car_SUV_Rusty1",
			"Exile_Car_SUV_Rusty2",
			"Exile_Car_SUV_Rusty3",
			"Exile_Car_Strider",
			"Exile_Car_Tempest",
			"Exile_Car_TowTractor_White",
			"Exile_Car_Tractor_Red",
			"Exile_Car_UAZ_Green",
			"Exile_Car_UAZ_Open_Green",
			"Exile_Car_Ural_Covered_Blue",
			"Exile_Car_Ural_Covered_Military",
			"Exile_Car_Ural_Covered_Worker",
			"Exile_Car_Ural_Covered_Yellow",
			"Exile_Car_Ural_Open_Blue",
			"Exile_Car_Ural_Open_Military",
			"Exile_Car_Ural_Open_Worker",
			"Exile_Car_Ural_Open_Yellow",
			"Exile_Car_V3S_Covered",
			"Exile_Car_V3S_Open",
			"Exile_Car_Van_Black",
			"Exile_Car_Van_Box_Black",
			"Exile_Car_Van_Box_Guerilla01",
			"Exile_Car_Van_Box_Guerilla02",
			"Exile_Car_Van_Box_Guerilla03",
			"Exile_Car_Van_Box_Guerilla04",
			"Exile_Car_Van_Box_Guerilla05",
			"Exile_Car_Van_Box_Guerilla06",
			"Exile_Car_Van_Box_Guerilla07",
			"Exile_Car_Van_Box_Guerilla08",
			"Exile_Car_Van_Box_Red",
			"Exile_Car_Van_Box_White",
			"Exile_Car_Van_Fuel_Black",
			"Exile_Car_Van_Fuel_Guerilla01",
			"Exile_Car_Van_Fuel_Guerilla02",
			"Exile_Car_Van_Fuel_Guerilla03",
			"Exile_Car_Van_Fuel_Red",
			"Exile_Car_Van_Fuel_White",
			"Exile_Car_Van_Guerilla01",
			"Exile_Car_Van_Guerilla02",
			"Exile_Car_Van_Guerilla03",
			"Exile_Car_Van_Guerilla04",
			"Exile_Car_Van_Guerilla05",
			"Exile_Car_Van_Guerilla06",
			"Exile_Car_Van_Guerilla07",
			"Exile_Car_Van_Guerilla08",
			"Exile_Car_Van_Red",
			"Exile_Car_Van_White",
			"Exile_Car_Volha_Black",
			"Exile_Car_Volha_Blue",
			"Exile_Car_Volha_White",
			"Exile_Car_Zamak",
			"B_LSV_01_armed_F",
			"B_LSV_01_armed_black_F",
			"B_LSV_01_armed_olive_F",
			"B_LSV_01_armed_sand_F",
			"B_T_LSV_01_armed_CTRG_F",
			"B_T_LSV_01_armed_black_F",
			"B_T_LSV_01_armed_olive_F",
			"B_T_LSV_01_armed_sand_F",
			"B_CTRG_LSV_01_light_F",
			"B_LSV_01_unarmed_F",
			"B_LSV_01_unarmed_black_F",
			"B_LSV_01_unarmed_olive_F",
			"B_LSV_01_unarmed_sand_F",
			"B_T_LSV_01_unarmed_CTRG_F",
			"B_T_LSV_01_unarmed_black_F",
			"B_T_LSV_01_unarmed_olive_F",
			"B_T_LSV_01_unarmed_sand_F",
			"O_LSV_02_armed_F",
			"O_LSV_02_armed_arid_F",
			"O_LSV_02_armed_black_F",
			"O_LSV_02_armed_ghex_F",
			"O_LSV_02_armed_viper_F",
			"O_T_LSV_02_armed_arid_F",
			"O_T_LSV_02_armed_black_F",
			"O_T_LSV_02_armed_ghex_F",
			"O_T_LSV_02_armed_viper_F",
			"O_LSV_02_unarmed_F",
			"O_LSV_02_unarmed_arid_F",
			"O_LSV_02_unarmed_black_F",
			"O_LSV_02_unarmed_ghex_F",
			"O_LSV_02_unarmed_viper_F",
			"O_T_LSV_02_unarmed_arid_F",
			"O_T_LSV_02_unarmed_black_F",
			"O_T_LSV_02_unarmed_ghex_F",
			"O_T_LSV_02_unarmed_viper_F",
			"C_Hatchback_01_F",
			"C_Hatchback_01_beigecustom_F",
			"C_Hatchback_01_black_F",
			"C_Hatchback_01_blue_F",
			"C_Hatchback_01_bluecustom_F",
			"C_Hatchback_01_dark_F",
			"C_Hatchback_01_green_F",
			"C_Hatchback_01_grey_F",
			"C_Hatchback_01_sport_F",
			"C_Hatchback_01_sport_blue_F",
			"C_Hatchback_01_sport_green_F",
			"C_Hatchback_01_sport_grey_F",
			"C_Hatchback_01_sport_orange_F",
			"C_Hatchback_01_sport_red_F",
			"C_Hatchback_01_sport_white_F",
			"C_Hatchback_01_white_F",
			"C_Hatchback_01_yellow_F",
			"C_Truck_02_box_F",
			"C_Truck_02_covered_F",
			"C_Truck_02_fuel_F",
			"C_Truck_02_transport_F",
			"C_Van_01_box_F",
			"C_Van_01_box_red_F",
			"C_Van_01_box_white_F",
			"C_Van_01_fuel_F",
			"C_Van_01_fuel_red_F",
			"C_Van_01_fuel_red_v2_F",
			"C_Van_01_fuel_white_F",
			"C_Van_01_fuel_white_v2_F",
			"C_Van_01_transport_F",
			"C_Van_01_transport_red_F",
			"C_Van_01_transport_white_F",
			"I_APC_Wheeled_03_cannon_F",
			"I_G_Offroad_01_F",
			"I_G_Offroad_01_armed_F",
			"I_G_Offroad_01_repair_F",
			"I_G_Van_01_fuel_F",
			"I_G_Van_01_transport_F",
			"I_MRAP_03_F",
			"I_MRAP_03_gmg_F",
			"I_MRAP_03_hmg_F",
			"I_Truck_02_ammo_F",
			"I_Truck_02_box_F",
			"I_Truck_02_covered_F",
			"I_Truck_02_fuel_F",
			"I_Truck_02_medical_F",
			"I_Truck_02_transport_F",
			"O_G_Offroad_01_F",
			"O_G_Offroad_01_armed_F",
			"O_G_Offroad_01_repair_F",
			"O_G_Van_01_fuel_F",
			"O_G_Van_01_transport_F",
			"O_MRAP_02_F",
			"O_MRAP_02_gmg_F",
			"O_MRAP_02_hmg_F",
			"O_T_MRAP_02_gmg_ghex_F",
			"O_T_MRAP_02_hmg_ghex_F",
			"O_Truck_02_Ammo_F",
			"O_Truck_02_box_F",
			"O_Truck_02_covered_F",
			"O_Truck_02_fuel_F",
			"O_Truck_02_medical_F",
			"O_Truck_02_transport_F",
			"O_Truck_03_ammo_F",
			"O_Truck_03_covered_F",
			"O_Truck_03_device_F",
			"O_Truck_03_fuel_F",
			"O_Truck_03_medical_F",
			"O_Truck_03_repair_F",
			"O_Truck_03_transport_F",
			"RHS_BTR70",
			"RHS_BTR70_MSV",
			"RHS_BTR70_VDV",
			"RHS_BTR70_VMF",
			"RHS_BTR70_VV",
			"RHS_BTR80A_MSV",
			"RHS_BTR80A_VDV",
			"RHS_BTR80A_VMF",
			"RHS_BTR80A_VV",
			"RHS_BTR80_MSV",
			"RHS_BTR80_VDV",
			"RHS_BTR80_VMF",
			"RHS_BTR80_VV",
			"RHS_M2A3",
			"RHS_M2A3_BUSKI",
			"RHS_Ural_Flat_MSV_01",
			"RHS_Ural_Flat_VDV_01",
			"RHS_Ural_Flat_VMF_01",
			"RHS_Ural_Flat_VV_01",
			"RHS_Ural_Fuel_MSV_01",
			"RHS_Ural_Fuel_VDV_01",
			"RHS_Ural_Fuel_VMF_01",
			"RHS_Ural_Fuel_VV_01",
			"RHS_Ural_MSV_01",
			"RHS_Ural_Open_Civ_01",
			"RHS_Ural_Open_Civ_02",
			"RHS_Ural_Open_Civ_03",
			"RHS_Ural_Open_Flat_MSV_01",
			"RHS_Ural_Open_Flat_VDV_01",
			"RHS_Ural_Open_Flat_VMF_01",
			"RHS_Ural_Open_Flat_VV_01",
			"RHS_Ural_Open_MSV_01",
			"RHS_Ural_Open_VDV_01",
			"RHS_Ural_Open_VMF_01",
			"RHS_Ural_Open_VV_01",
			"RHS_Ural_VDV_01",
			"RHS_Ural_VMF_01",
			"RHS_Ural_VV_01",
			"RHS_Civ_Truck_02_covered_F",
			"RHS_Civ_Truck_02_transport_F",
			"RHS_Ural_Civ_01",
			"RHS_Ural_Civ_02",
			"RHS_Ural_Civ_03",
			"RHS_Ural_Repair_MSV_01",
			"RHS_Ural_Repair_VDV_01",
			"RHS_Ural_Repair_VMF_01",
			"RHS_Ural_Repair_VV_01",
			"rhs_bmp3_late_msv",
			"rhs_bmp3mera_msv",
			"rhs_btr60_chdkz",
			"rhs_btr60_msv",
			"rhs_btr60_vdv",
			"rhs_btr60_vmf",
			"rhs_btr60_vv",
			"rhs_btr70_chdkz",
			"rhs_gaz66_ammo_vmf",
			"rhs_gaz66_flat_msv",
			"rhs_gaz66_flat_vdv",
			"rhs_gaz66_flat_vmf",
			"rhs_gaz66_flat_vv",
			"rhs_gaz66_msv",
			"rhs_gaz66_r142_msv",
			"rhs_gaz66_r142_vdv",
			"rhs_gaz66_r142_vmf",
			"rhs_gaz66_r142_vv",
			"rhs_gaz66_repair_msv",
			"rhs_gaz66_repair_vdv",
			"rhs_gaz66_repair_vmf",
			"rhs_gaz66_repair_vv",
			"rhs_gaz66_vmf",
			"rhs_gaz66_vv",
			"rhs_gaz66o_flat_msv",
			"rhs_gaz66o_flat_vdv",
			"rhs_gaz66o_flat_vmf",
			"rhs_gaz66o_flat_vv",
			"rhs_gaz66o_msv",
			"rhs_gaz66o_vdv",
			"rhs_gaz66o_vmf",
			"rhs_gaz66o_vv",
			"rhs_t72ba_tv",
			"rhs_t72bc_tv",
			"rhs_tigr_3camo_vdv",
			"rhs_tigr_ffv_3camo_vdv",
			"rhs_tigr_ffv_vdv",
			"rhs_tigr_sts_3camo_vdv",
			"rhs_tigr_vdv",
			"rhs_typhoon_vdv",
			"rhs_uaz_ags_chdkz",
			"rhs_uaz_dshkm_chdkz",
			"rhs_uaz_open_chdkz",
			"rhs_uaz_open_vmf",
			"rhs_uaz_spg9_chdkz",
			"rhs_uaz_vmf",
			"RHS_UAZ_MSV_01",
			"rhs_uaz_open_MSV_01",
			"rhs_uaz_open_vdv",
			"rhs_uaz_open_vv",
			"rhs_uaz_vdv",
			"rhs_uaz_vv",
			"rhs_kamaz5350",
			"rhs_kamaz5350_flatbed",
			"rhs_kamaz5350_flatbed_cover",
			"rhs_kamaz5350_flatbed_cover_msv",
			"rhs_kamaz5350_flatbed_cover_vdv",
			"rhs_kamaz5350_flatbed_cover_vmf",
			"rhs_kamaz5350_flatbed_cover_vv",
			"rhs_kamaz5350_flatbed_msv",
			"rhs_kamaz5350_flatbed_vdv",
			"rhs_kamaz5350_flatbed_vmf",
			"rhs_kamaz5350_flatbed_vv",
			"rhs_kamaz5350_msv",
			"rhs_kamaz5350_open",
			"rhs_kamaz5350_open_msv",
			"rhs_kamaz5350_open_vdv",
			"rhs_kamaz5350_open_vmf",
			"rhs_kamaz5350_open_vv",
			"rhs_kamaz5350_vdv",
			"rhs_kamaz5350_vmf",
			"rhs_kamaz5350_vv",
			"rhs_ural_chdkz",
			"rhs_ural_open_chdkz",
			"rhs_ural_work_chdkz",
			"rhs_ural_work_open_chdkz",
			"rhsusf_M1078A1P2_B_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_D_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_WD_CP_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_fmtv_usarmy",
			"rhsusf_M1078A1P2_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1078A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1083A1P2_B_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_d_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_MHQ_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_Medical_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_M2_wd_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_fmtv_usarmy",
			"rhsusf_M1083A1P2_B_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_fmtv_usarmy",
			"rhsusf_M1083A1P2_D_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_fmtv_usarmy",
			"rhsusf_M1083A1P2_WD_open_fmtv_usarmy",
			"rhsusf_M1083A1P2_flatbed_fmtv_usarmy",
			"rhsusf_M1083A1P2_fmtv_usarmy",
			"rhsusf_M1083A1P2_open_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_M2_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_B_fmtv_usarmy",
			"rhsusf_M1084A1P2_D_fmtv_usarmy",
			"rhsusf_M1084A1P2_WD_fmtv_usarmy",
			"rhsusf_M1084A1P2_fmtv_usarmy",
			"rhsusf_M1084A1R_SOV_M2_D_fmtv_socom",
			"rhsusf_M1084A1R_SOV_M2_WD_fmtv_socom",
			"rhsusf_M1085A1P2_B_D_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_Medical_fmtv_usarmy",
			"rhsusf_M1085A1P2_B_WD_Medical_fmtv_usarmy",
			"rhsusf_M1232_M2_usarmy_d",
			"rhsusf_M1232_M2_usarmy_wd",
			"rhsusf_M1232_MK19_usarmy_d",
			"rhsusf_M1232_MK19_usarmy_wd",
			"rhsusf_M1232_usarmy_d",
			"rhsusf_M1232_usarmy_wd",
			"rhsusf_M1237_M2_usarmy_d",
			"rhsusf_M1237_M2_usarmy_wd",
			"rhsusf_M1237_MK19_usarmy_d",
			"rhsusf_M1237_MK19_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_d",
			"rhsusf_M977A4_AMMO_BKIT_usarmy_wd",
			"rhsusf_M977A4_AMMO_usarmy_d",
			"rhsusf_M977A4_AMMO_usarmy_wd",
			"rhsusf_M977A4_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_BKIT_usarmy_d",
			"rhsusf_M977A4_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_d",
			"rhsusf_M977A4_REPAIR_BKIT_usarmy_wd",
			"rhsusf_M977A4_REPAIR_usarmy_d",
			"rhsusf_M977A4_REPAIR_usarmy_wd",
			"rhsusf_M977A4_usarmy_d",
			"rhsusf_M977A4_usarmy_wd",
			"rhsusf_M978A4_BKIT_usarmy_d",
			"rhsusf_M978A4_BKIT_usarmy_wd",
			"rhsusf_M978A4_usarmy_d",
			"rhsusf_M978A4_usarmy_wd",
			"rhsusf_m1025_d",
			"rhsusf_m1025_d_Mk19",
			"rhsusf_m1025_d_m2",
			"rhsusf_m1025_d_s",
			"rhsusf_m1025_d_s_Mk19",
			"rhsusf_m1025_d_s_m2",
			"rhsusf_m1025_w",
			"rhsusf_m1025_w_m2",
			"rhsusf_m1025_w_mk19",
			"rhsusf_m1025_w_s",
			"rhsusf_m1025_w_s_Mk19",
			"rhsusf_m1025_w_s_m2",
			"rhsusf_m113_usarmy_M240",
			"rhsusf_m113_usarmy_MK19",
			"rhsusf_m113_usarmy_supply",
			"rhsusf_m113_usarmy_unarmed",
			"rhsusf_m113d_usarmy",
			"rhsusf_m113d_usarmy_M240",
			"rhsusf_m113d_usarmy_MK19",
			"rhsusf_m113d_usarmy_medical",
			"rhsusf_m113d_usarmy_supply",
			"rhsusf_m113d_usarmy_unarmed",
			"rhsusf_m1a1aimwd_usarmy",
			"rhsusf_m1a2sep1tuskiiwd_usarmy",
			"rhsusf_m998_d_2dr",
			"rhsusf_m998_d_2dr_fulltop",
			"rhsusf_m998_d_2dr_halftop",
			"rhsusf_m998_d_4dr",
			"rhsusf_m998_d_4dr_fulltop",
			"rhsusf_m998_d_4dr_halftop",
			"rhsusf_m998_d_s_2dr",
			"rhsusf_m998_d_s_2dr_fulltop",
			"rhsusf_m998_d_s_2dr_halftop",
			"rhsusf_m998_d_s_4dr",
			"rhsusf_m998_d_s_4dr_fulltop",
			"rhsusf_m998_d_s_4dr_halftop",
			"rhsusf_m998_w_2dr",
			"rhsusf_m998_w_2dr_fulltop",
			"rhsusf_m998_w_2dr_halftop",
			"rhsusf_m998_w_4dr",
			"rhsusf_m998_w_4dr_fulltop",
			"rhsusf_m998_w_4dr_halftop",
			"rhsusf_m998_w_s_2dr",
			"rhsusf_m998_w_s_2dr_fulltop",
			"rhsusf_m998_w_s_2dr_halftop",
			"rhsusf_m998_w_s_4dr",
			"rhsusf_m998_w_s_4dr_fulltop",
			"rhsusf_m998_w_s_4dr_halftop",
			"rhsusf_mrzr4_d",
			"rhsusf_mrzr4_d_mud",
			"rhsusf_mrzr4_w",
			"rhsusf_mrzr4_w_mud",
			"rhsusf_rg33_d",
			"rhsusf_rg33_m2_d",
			"rhsusf_rg33_m2_usmc_d",
			"rhsusf_rg33_m2_usmc_wd",
			"rhsusf_rg33_m2_wd",
			"rhsusf_rg33_usmc_d",
			"rhsusf_rg33_usmc_wd",
			"rhsusf_rg33_wd",
			"volha_Civ_01",
			"volha_Civ_02",
			"volha_Civ_03",
			"rhs_truck",
			"rhs_gaz66_ammo_msv",
			"rhs_gaz66_ammo_vdv",
			"rhs_gaz66_ammo_vv",
			"rhs_gaz66_ap2_msv",
			"rhs_gaz66_ap2_vdv",
			"rhs_gaz66_ap2_vmf",
			"rhs_gaz66_ap2_vv",
			"rhs_gaz66_vdv",
			"rhs_tigr_3camo_vmf",
			"rhs_tigr_3camo_vv",
			"rhs_tigr_ffv_3camo_msv",
			"rhs_tigr_ffv_3camo_vmf",
			"rhs_tigr_ffv_3camo_vv",
			"rhs_tigr_ffv_msv",
			"rhs_tigr_ffv_vmf",
			"rhs_tigr_ffv_vv",
			"rhs_tigr_m_3camo_msv",
			"rhs_tigr_m_3camo_vdv",
			"rhs_tigr_m_3camo_vmf",
			"rhs_tigr_m_3camo_vv",
			"rhs_tigr_m_msv",
			"rhs_tigr_m_vdv",
			"rhs_tigr_m_vmf",
			"rhs_tigr_m_vv",
			"rhs_tigr_msv",
			"rhs_tigr_sts_3camo_msv",
			"rhs_tigr_sts_3camo_vmf",
			"rhs_tigr_sts_3camo_vv",
			"rhs_tigr_sts_msv",
			"rhs_tigr_sts_vdv",
			"rhs_tigr_sts_vmf",
			"rhs_tigr_sts_vv",
			"rhs_tigr_vmf",
			"rhs_tigr_vv",
			"Exile_Container_SupplyBox"
	];

/**
 * List of class names of vehicles or cargo objects which can transport objects.
 * The second element of the nested arrays is the load capacity (in relation with the capacity cost of the objects).
 */
R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
	[
			["B_APC_Wheeled_01_cannon_F", 160],
			["B_Boat_Armed_01_minigun_F", 80],
			["B_Boat_Transport_01_F", 80],
			["B_G_Boat_Transport_01_F", 80],
			["B_G_Offroad_01_F", 80],
			["B_G_Offroad_01_armed_F", 80],
			["B_G_Offroad_01_repair_F", 80],
			["B_G_Van_01_fuel_F", 160],
			["B_G_Van_01_transport_F", 160],
			["B_Heli_Attack_01_F", 160],
			["B_Heli_Attack_01_dynamicLoadout_F", 160],
			["B_Heli_Light_01_F", 160],
			["B_Heli_Light_01_armed_F", 160],
			["B_Heli_Light_01_dynamicLoadout_F", 160],
			["B_Heli_Light_01_stripped_F", 160],
			["B_Heli_Transport_01_F", 160],
			["B_Heli_Transport_01_camo_F", 160],
			["B_Heli_Transport_03_F", 160],
			["B_Heli_Transport_03_black_F", 160],
			["B_Heli_Transport_03_unarmed_F", 160],
			["B_Heli_Transport_03_unarmed_green_F", 160],
			["B_MRAP_01_F", 80],
			["B_MRAP_01_gmg_F", 80],
			["B_MRAP_01_hmg_F", 80],
			["B_T_VTOL_01_infantry_F", 200],
			["B_T_VTOL_01_vehicle_F", 200],
			["B_Truck_01_Repair_F", 160],
			["B_Truck_01_ammo_F", 160],
			["B_Truck_01_box_F", 160],
			["B_Truck_01_covered_F", 160],
			["B_Truck_01_fuel_F", 160],
			["B_Truck_01_medical_F", 160],
			["B_Truck_01_mover_F", 160],
			["B_Truck_01_transport_F", 160],
			["C_Heli_light_01_blueLine_F", 80],
			["C_Heli_light_01_blue_F", 80],
			["C_Heli_light_01_digital_F", 80],
			["C_Heli_light_01_elliptical_F", 80],
			["C_Heli_light_01_furious_F", 80],
			["C_Heli_light_01_graywatcher_F", 80],
			["C_Heli_light_01_ion_F", 80],
			["C_Heli_light_01_jeans_F", 80],
			["C_Heli_light_01_light_F", 80],
			["C_Heli_light_01_luxe_F", 80],
			["C_Heli_light_01_red_F", 80],
			["C_Heli_light_01_shadow_F", 80],
			["C_Heli_light_01_sheriff_F", 80],
			["C_Heli_light_01_speedy_F", 80],
			["C_Heli_light_01_stripped_F", 80],
			["C_Heli_light_01_sunset_F", 80],
			["C_Heli_light_01_vrana_F", 80],
			["C_Heli_light_01_wasp_F", 80],
			["C_Heli_light_01_wave_F", 80],
			["C_IDAP_Offroad_01_F", 120],
			["C_IDAP_Offroad_02_unarmed_F", 120],
			["C_IDAP_Truck_02_F", 120],
			["C_IDAP_Truck_02_transport_F", 120],
			["C_IDAP_Truck_02_water_F", 120],
			["C_Offroad_01_F", 120],
			["C_Offroad_01_blue_F", 120],
			["C_Offroad_01_bluecustom_F", 120],
			["C_Offroad_01_darkred_F", 120],
			["C_Offroad_01_red_F", 120],
			["C_Offroad_01_repair_F", 120],
			["C_Offroad_01_sand_F", 120],
			["C_Offroad_01_white_F", 120],
			["C_Offroad_default_F", 120],
			["C_Offroad_luxe_F", 120],
			["C_Offroad_stripped_F", 120],
			["B_LSV_01_armed_F", 160],
			["B_LSV_01_armed_black_F", 160],
			["B_LSV_01_armed_olive_F", 160],
			["B_LSV_01_armed_sand_F", 160],
			["B_T_LSV_01_armed_CTRG_F", 160],
			["B_T_LSV_01_armed_black_F", 160],
			["B_T_LSV_01_armed_olive_F", 160],
			["B_T_LSV_01_armed_sand_F", 160],
			["B_CTRG_LSV_01_light_F", 160],
			["B_LSV_01_unarmed_F", 160],
			["B_LSV_01_unarmed_black_F", 160],
			["B_LSV_01_unarmed_olive_F", 160],
			["B_LSV_01_unarmed_sand_F", 160],
			["B_T_LSV_01_unarmed_CTRG_F", 160],
			["B_T_LSV_01_unarmed_black_F", 160],
			["B_T_LSV_01_unarmed_olive_F", 160],
			["B_T_LSV_01_unarmed_sand_F", 160],
			["O_LSV_02_armed_F", 160],
			["O_LSV_02_armed_arid_F", 160],
			["O_LSV_02_armed_black_F", 160],
			["O_LSV_02_armed_ghex_F", 160],
			["O_LSV_02_armed_viper_F", 160],
			["O_T_LSV_02_armed_arid_F", 160],
			["O_T_LSV_02_armed_black_F", 160],
			["O_T_LSV_02_armed_ghex_F", 160],
			["O_T_LSV_02_armed_viper_F", 160],
			["O_LSV_02_unarmed_F", 160],
			["O_LSV_02_unarmed_arid_F", 160],
			["O_LSV_02_unarmed_black_F", 160],
			["O_LSV_02_unarmed_ghex_F", 160],
			["O_LSV_02_unarmed_viper_F", 160],
			["O_T_LSV_02_unarmed_arid_F", 160],
			["O_T_LSV_02_unarmed_black_F", 160],
			["O_T_LSV_02_unarmed_ghex_F", 160],
			["O_T_LSV_02_unarmed_viper_F", 160],
			["Exile_Car_BRDM2_HQ", 160],
			["Exile_Car_BTR40_Camo", 160],
			["Exile_Car_BTR40_Green", 160],
			["Exile_Car_BTR40_MG_Camo", 160],
			["Exile_Car_BTR40_MG_Green", 160],
			["Exile_Car_Golf_Black", 80],
			["Exile_Car_Golf_Red", 80],
			["Exile_Car_HEMMT", 320],
			["Exile_Car_HMMWV_M134_Green", 120],
			["Exile_Car_HMMWV_M2_Green", 120],
			["Exile_Car_HMMWV_MEV_Green", 120],
			["Exile_Car_HMMWV_UNA_Green", 120],
			["Exile_Car_Hatchback_Beige", 80],
			["Exile_Car_Hatchback_BeigeCustom", 80],
			["Exile_Car_Hatchback_Black", 80],
			["Exile_Car_Hatchback_Blue", 80],
			["Exile_Car_Hatchback_BlueCustom", 80],
			["Exile_Car_Hatchback_Dark", 80],
			["Exile_Car_Hatchback_Green", 80],
			["Exile_Car_Hatchback_Grey", 80],
			["Exile_Car_Hatchback_Rusty1", 80],
			["Exile_Car_Hatchback_Rusty2", 80],
			["Exile_Car_Hatchback_Rusty3", 80],
			["Exile_Car_Hatchback_Sport_Beige", 60],
			["Exile_Car_Hatchback_Sport_Blue", 60],
			["Exile_Car_Hatchback_Sport_Green", 60],
			["Exile_Car_Hatchback_Sport_Orange", 60],
			["Exile_Car_Hatchback_Sport_Red", 60],
			["Exile_Car_Hatchback_Sport_White", 60],
			["Exile_Car_Hatchback_Yellow", 80],
			["Exile_Car_Hunter", 160],
			["Exile_Car_Ifrit", 160],
			["Exile_Car_Ikarus_Blue", 160],
			["Exile_Car_Lada_Green", 40],
			["Exile_Car_Lada_Hipster", 40],
			["Exile_Car_Lada_Red", 40],
			["Exile_Car_Lada_Taxi", 40],
			["Exile_Car_Lada_White", 40],
			["Exile_Car_LandRover_Ambulance_Desert", 120],
			["Exile_Car_LandRover_Ambulance_Green", 120],
			["Exile_Car_LandRover_Ambulance_Sand", 120],
			["Exile_Car_LandRover_Desert", 120],
			["Exile_Car_LandRover_Green", 120],
			["Exile_Car_LandRover_Red", 120],
			["Exile_Car_LandRover_Sand", 120],
			["Exile_Car_LandRover_Urban", 120],
			["Exile_Car_MB4WD", 100],
			["Exile_Car_MB4WDOpen", 100],
			["Exile_Car_Octavius_Black", 80],
			["Exile_Car_Octavius_White", 80],
			["Exile_Car_Offroad_Armed_Guerilla01", 80],
			["Exile_Car_Offroad_Armed_Guerilla02", 80],
			["Exile_Car_Offroad_Armed_Guerilla03", 80],
			["Exile_Car_Offroad_Armed_Guerilla04", 80],
			["Exile_Car_Offroad_Armed_Guerilla05", 80],
			["Exile_Car_Offroad_Armed_Guerilla06", 80],
			["Exile_Car_Offroad_Armed_Guerilla07", 80],
			["Exile_Car_Offroad_Armed_Guerilla08", 80],
			["Exile_Car_Offroad_Armed_Guerilla09", 80],
			["Exile_Car_Offroad_Armed_Guerilla10", 80],
			["Exile_Car_Offroad_Armed_Guerilla11", 80],
			["Exile_Car_Offroad_Armed_Guerilla12", 80],
			["Exile_Car_Offroad_Beige", 80],
			["Exile_Car_Offroad_Blue", 80],
			["Exile_Car_Offroad_BlueCustom", 80],
			["Exile_Car_Offroad_DarkRed", 80],
			["Exile_Car_Offroad_Guerilla01", 80],
			["Exile_Car_Offroad_Guerilla02", 80],
			["Exile_Car_Offroad_Guerilla03", 80],
			["Exile_Car_Offroad_Guerilla04", 80],
			["Exile_Car_Offroad_Guerilla05", 80],
			["Exile_Car_Offroad_Guerilla06", 80],
			["Exile_Car_Offroad_Guerilla07", 80],
			["Exile_Car_Offroad_Guerilla08", 80],
			["Exile_Car_Offroad_Guerilla09", 80],
			["Exile_Car_Offroad_Guerilla10", 80],
			["Exile_Car_Offroad_Guerilla11", 80],
			["Exile_Car_Offroad_Guerilla12", 80],
			["Exile_Car_Offroad_Red", 80],
			["Exile_Car_Offroad_Repair_Beige", 80],
			["Exile_Car_Offroad_Repair_Blue", 80],
			["Exile_Car_Offroad_Repair_BlueCustom", 80],
			["Exile_Car_Offroad_Repair_Civillian", 80],
			["Exile_Car_Offroad_Repair_DarkRed", 80],
			["Exile_Car_Offroad_Repair_Guerilla01", 80],
			["Exile_Car_Offroad_Repair_Guerilla02", 80],
			["Exile_Car_Offroad_Repair_Guerilla03", 80],
			["Exile_Car_Offroad_Repair_Guerilla04", 80],
			["Exile_Car_Offroad_Repair_Guerilla05", 80],
			["Exile_Car_Offroad_Repair_Guerilla06", 80],
			["Exile_Car_Offroad_Repair_Guerilla07", 80],
			["Exile_Car_Offroad_Repair_Guerilla08", 80],
			["Exile_Car_Offroad_Repair_Guerilla09", 80],
			["Exile_Car_Offroad_Repair_Guerilla10", 80],
			["Exile_Car_Offroad_Repair_Guerilla11", 80],
			["Exile_Car_Offroad_Repair_Guerilla12", 80],
			["Exile_Car_Offroad_Repair_Red", 80],
			["Exile_Car_Offroad_Repair_White", 80],
			["Exile_Car_Offroad_Rusty1", 80],
			["Exile_Car_Offroad_Rusty2", 80],
			["Exile_Car_Offroad_Rusty3", 80],
			["Exile_Car_Offroad_White", 80],
			["Exile_Car_OldTractor_Red", 80],
			["Exile_Car_SUVXL_Black", 120],
			["Exile_Car_SUV_Armed_Black", 80],
			["Exile_Car_SUV_Black", 40],
			["Exile_Car_SUV_Grey", 40],
			["Exile_Car_SUV_Orange", 40],
			["Exile_Car_SUV_Red", 40],
			["Exile_Car_SUV_Rusty1", 40],
			["Exile_Car_SUV_Rusty2", 40],
			["Exile_Car_SUV_Rusty3", 40],
			["Exile_Car_Strider", 160],
			["Exile_Car_Tempest", 320],
			["Exile_Car_TowTractor_White", 40],
			["Exile_Car_Tractor_Red", 80],
			["Exile_Car_UAZ_Green", 240],
			["Exile_Car_UAZ_Open_Green", 240],
			["Exile_Car_Ural_Covered_Blue", 240],
			["Exile_Car_Ural_Covered_Military", 240],
			["Exile_Car_Ural_Covered_Worker", 240],
			["Exile_Car_Ural_Covered_Yellow", 240],
			["Exile_Car_Ural_Open_Blue", 240],
			["Exile_Car_Ural_Open_Military", 240],
			["Exile_Car_Ural_Open_Worker", 240],
			["Exile_Car_Ural_Open_Yellow", 240],
			["Exile_Car_V3S_Covered", 160],
			["Exile_Car_V3S_Open", 160],
			["Exile_Car_Van_Black", 160],
			["Exile_Car_Van_Box_Black", 160],
			["Exile_Car_Van_Box_Guerilla01", 160],
			["Exile_Car_Van_Box_Guerilla02", 160],
			["Exile_Car_Van_Box_Guerilla03", 160],
			["Exile_Car_Van_Box_Guerilla04", 160],
			["Exile_Car_Van_Box_Guerilla05", 160],
			["Exile_Car_Van_Box_Guerilla06", 160],
			["Exile_Car_Van_Box_Guerilla07", 160],
			["Exile_Car_Van_Box_Guerilla08", 160],
			["Exile_Car_Van_Box_Red", 160],
			["Exile_Car_Van_Box_White", 160],
			["Exile_Car_Van_Fuel_Black", 80],
			["Exile_Car_Van_Fuel_Guerilla01", 80],
			["Exile_Car_Van_Fuel_Guerilla02", 80],
			["Exile_Car_Van_Fuel_Guerilla03", 80],
			["Exile_Car_Van_Fuel_Red", 80],
			["Exile_Car_Van_Fuel_White", 80],
			["Exile_Car_Van_Guerilla01", 160],
			["Exile_Car_Van_Guerilla02", 160],
			["Exile_Car_Van_Guerilla03", 160],
			["Exile_Car_Van_Guerilla04", 160],
			["Exile_Car_Van_Guerilla05", 160],
			["Exile_Car_Van_Guerilla06", 160],
			["Exile_Car_Van_Guerilla07", 160],
			["Exile_Car_Van_Guerilla08", 160],
			["Exile_Car_Van_Red", 160],
			["Exile_Car_Van_White", 160],
			["Exile_Car_Volha_Black", 80],
			["Exile_Car_Volha_Blue", 80],
			["Exile_Car_Volha_White", 80],
			["Exile_Car_Zamak", 320],
			["Exile_Chopper_Hellcat_FIA", 120],
			["Exile_Chopper_Hellcat_Green", 120],
			["Exile_Chopper_Hellcat_Green", 120],
			["Exile_Chopper_Huey_Armed_Desert", 120],
			["Exile_Chopper_Huey_Armed_Green", 120],
			["Exile_Chopper_Huey_Desert", 120],
			["Exile_Chopper_Huey_Green", 120],
			["Exile_Chopper_Hummingbird_Civillian_Blue", 80],
			["Exile_Chopper_Hummingbird_Civillian_BlueLine", 80],
			["Exile_Chopper_Hummingbird_Civillian_Digital", 80],
			["Exile_Chopper_Hummingbird_Civillian_Elliptical", 80],
			["Exile_Chopper_Hummingbird_Civillian_Furious", 80],
			["Exile_Chopper_Hummingbird_Civillian_GrayWatcher", 80],
			["Exile_Chopper_Hummingbird_Civillian_ION", 80],
			["Exile_Chopper_Hummingbird_Civillian_Jeans", 80],
			["Exile_Chopper_Hummingbird_Civillian_Light", 80],
			["Exile_Chopper_Hummingbird_Civillian_Red", 80],
			["Exile_Chopper_Hummingbird_Civillian_Shadow", 80],
			["Exile_Chopper_Hummingbird_Civillian_Sheriff", 80],
			["Exile_Chopper_Hummingbird_Civillian_Speedy", 80],
			["Exile_Chopper_Hummingbird_Civillian_Sunset", 80],
			["Exile_Chopper_Hummingbird_Civillian_Vrana", 80],
			["Exile_Chopper_Hummingbird_Civillian_Wasp", 80],
			["Exile_Chopper_Hummingbird_Civillian_Wasp", 80],
			["Exile_Chopper_Hummingbird_Civillian_Wave", 80],
			["Exile_Chopper_Hummingbird_Green", 80],
			["Exile_Chopper_Huron_Black", 160],
			["Exile_Chopper_Huron_Green", 160],
			["Exile_Chopper_Mohawk_FIA", 160],
			["Exile_Chopper_Orca_Black", 120],
			["Exile_Chopper_Orca_BlackCustom", 120],
			["Exile_Chopper_Orca_CSAT", 120],
			["Exile_Chopper_Taru_Black", 160],
			["Exile_Chopper_Taru_CSAT", 160],
			["Exile_Chopper_Taru_Covered_Black", 160],
			["Exile_Chopper_Taru_Covered_CSAT", 160],
			["Exile_Chopper_Taru_Transport_Black", 160],
			["Exile_Chopper_Taru_Transport_CSAT", 160],
			["C_Hatchback_01_F", 80],
			["C_Hatchback_01_beigecustom_F", 80],
			["C_Hatchback_01_black_F", 80],
			["C_Hatchback_01_blue_F", 80],
			["C_Hatchback_01_bluecustom_F", 80],
			["C_Hatchback_01_dark_F", 80],
			["C_Hatchback_01_green_F", 80],
			["C_Hatchback_01_grey_F", 80],
			["C_Hatchback_01_sport_F", 80],
			["C_Hatchback_01_sport_blue_F", 80],
			["C_Hatchback_01_sport_green_F", 80],
			["C_Hatchback_01_sport_grey_F", 80],
			["C_Hatchback_01_sport_orange_F", 80],
			["C_Hatchback_01_sport_red_F", 80],
			["C_Hatchback_01_sport_white_F", 80],
			["C_Hatchback_01_white_F", 80],
			["C_Hatchback_01_yellow_F", 80],
			["C_Truck_02_box_F", 160],
			["C_Truck_02_covered_F", 160],
			["C_Truck_02_fuel_F", 160],
			["C_Truck_02_transport_F", 160],
			["C_Van_01_box_F", 160],
			["C_Van_01_box_red_F", 160],
			["C_Van_01_box_white_F", 160],
			["C_Van_01_fuel_F", 160],
			["C_Van_01_fuel_red_F", 160],
			["C_Van_01_fuel_red_v2_F", 160],
			["C_Van_01_fuel_white_F", 160],
			["C_Van_01_fuel_white_v2_F", 160],
			["C_Van_01_transport_F", 160],
			["C_Van_01_transport_red_F", 160],
			["C_Van_01_transport_white_F", 160],
			["I_APC_Wheeled_03_cannon_F", 160],
			["I_Boat_Armed_01_minigun_F", 80],
			["I_Boat_Transport_01_F", 80],
			["I_G_Boat_Transport_01_F", 80],
			["I_G_Offroad_01_F", 160],
			["I_G_Offroad_01_F", 80],
			["I_G_Offroad_01_armed_F", 160],
			["I_G_Offroad_01_repair_F", 160],
			["I_G_Van_01_fuel_F", 160],
			["I_G_Van_01_transport_F", 160],
			["I_Heli_Transport_02_F", 160],
			["I_Heli_light_03_F", 160],
			["I_Heli_light_03_dynamicLoadout_F", 160],
			["I_Heli_light_03_unarmed_F", 160],
			["I_MRAP_03_F", 80],
			["I_MRAP_03_gmg_F", 80],
			["I_MRAP_03_hmg_F", 80],
			["I_SDV_01_F", 80],
			["I_Truck_02_ammo_F", 160],
			["I_Truck_02_box_F", 160],
			["I_Truck_02_covered_F", 160],
			["I_Truck_02_fuel_F", 160],
			["I_Truck_02_medical_F", 160],
			["I_Truck_02_transport_F", 160],
			["O_Boat_Armed_01_hmg_F", 80],
			["O_Boat_Transport_01_F", 80],
			["O_G_Boat_Transport_01_F", 80],
			["O_G_Offroad_01_F", 160],
			["O_G_Offroad_01_armed_F", 160],
			["O_G_Offroad_01_repair_F", 160],
			["O_G_Van_01_fuel_F", 160],
			["O_G_Van_01_transport_F", 160],
			["O_Heli_Attack_02_F", 160],
			["O_Heli_Attack_02_black_F", 160],
			["O_Heli_Attack_02_dynamicLoadout_F", 160],
			["O_Heli_Attack_02_dynamicLoadout_black_F", 160],
			["O_Heli_Light_02_F", 160],
			["O_Heli_Light_02_dynamicLoadout_F", 160],
			["O_Heli_Light_02_unarmed_F", 160],
			["O_Heli_Light_02_v2_F", 160],
			["O_Heli_Transport_04_F", 160],
			["O_Heli_Transport_04_ammo_F", 160],
			["O_Heli_Transport_04_ammo_black_F", 160],
			["O_Heli_Transport_04_bench_F", 160],
			["O_Heli_Transport_04_bench_black_F", 160],
			["O_Heli_Transport_04_black_F", 160],
			["O_Heli_Transport_04_box_F", 160],
			["O_Heli_Transport_04_box_black_F", 160],
			["O_Heli_Transport_04_covered_F", 160],
			["O_Heli_Transport_04_covered_black_F", 160],
			["O_Heli_Transport_04_fuel_F", 160],
			["O_Heli_Transport_04_fuel_black_F", 160],
			["O_Heli_Transport_04_medevac_F", 160],
			["O_Heli_Transport_04_medevac_black_F", 160],
			["O_Heli_Transport_04_repair_F", 160],
			["O_Heli_Transport_04_repair_black_F", 160],
			["O_MRAP_02_F", 80],
			["O_MRAP_02_gmg_F", 80],
			["O_MRAP_02_hmg_F", 80],
			["O_SDV_01_F", 80],
			["O_T_MRAP_02_gmg_ghex_F", 160],
			["O_T_MRAP_02_hmg_ghex_F", 160],
			["O_Truck_02_Ammo_F", 160],
			["O_Truck_02_box_F", 160],
			["O_Truck_02_covered_F", 160],
			["O_Truck_02_fuel_F", 160],
			["O_Truck_02_medical_F", 160],
			["O_Truck_02_transport_F", 160],
			["O_Truck_03_ammo_F", 160],
			["O_Truck_03_covered_F", 160],
			["O_Truck_03_device_F", 160],
			["O_Truck_03_fuel_F", 160],
			["O_Truck_03_medical_F", 160],
			["O_Truck_03_repair_F", 160],
			["O_Truck_03_transport_F", 160],
			["RHS_AH1Z", 160],
			["RHS_AH1Z_CS", 160],
			["RHS_AH1Z_GS", 160],
			["RHS_AH1Z_wd", 160],
			["RHS_AH1Z_wd_CS", 160],
			["RHS_AH1Z_wd_GS", 160],
			["RHS_AH64D", 160],
			["RHS_AH64DGrey", 160],
			["RHS_AH64D_AA", 160],
			["RHS_AH64D_CS", 160],
			["RHS_AH64D_GS", 160],
			["RHS_AH64D_wd", 160],
			["RHS_AH64D_wd_AA", 160],
			["RHS_AH64D_wd_CS", 160],
			["RHS_AH64D_wd_GS", 160],
			["RHS_BTR70", 160],
			["RHS_BTR70_MSV", 160],
			["RHS_BTR70_VDV", 160],
			["RHS_BTR70_VMF", 160],
			["RHS_BTR70_VV", 160],
			["RHS_BTR80A_MSV", 160],
			["RHS_BTR80A_VDV", 160],
			["RHS_BTR80A_VMF", 160],
			["RHS_BTR80A_VV", 160],
			["RHS_BTR80_MSV", 160],
			["RHS_BTR80_VDV", 160],
			["RHS_BTR80_VMF", 160],
			["RHS_BTR80_VV", 160],
			["RHS_CH_47F", 160],
			["RHS_CH_47F_10", 160],
			["RHS_CH_47F_light", 160],
			["RHS_Ka52_UPK23_vvs", 160],
			["RHS_Ka52_UPK23_vvsc", 160],
			["RHS_Ka52_vvs", 160],
			["RHS_Ka52_vvsc", 160],
			["RHS_M2A3", 160],
			["RHS_M2A3_BUSKI", 160],
			["RHS_MELB_AH6M", 160],
			["RHS_MELB_AH6M_H", 160],
			["RHS_MELB_AH6M_M",  160],
			["RHS_MELB_H6M", 160],
			["RHS_MELB_MH6M", 160],
			["RHS_MI8MTV3_UPK23_vvs", 160],
			["RHS_MI8MTV3_UPK23_vvsc", 160],
			["RHS_MI8MTV3_vvs", 160],
			["RHS_MI8MTV3_vvsc", 160],
			["RHS_Mi24P_AT_vdv", 160],
			["RHS_Mi24P_AT_vvs", 160],
			["RHS_Mi24P_AT_vvsc", 160],
			["RHS_Mi24P_CAS_vdv", 160],
			["RHS_Mi24P_CAS_vvs", 160],
			["RHS_Mi24P_CAS_vvsc", 160],
			["RHS_Mi24P_vdv", 160],
			["RHS_Mi24P_vvs", 160],
			["RHS_Mi24P_vvsc", 160],
			["RHS_Mi24V_AT_vdv", 160],
			["RHS_Mi24V_AT_vvs", 160],
			["RHS_Mi24V_AT_vvsc", 160],
			["RHS_Mi24V_FAB_vdv", 160],
			["RHS_Mi24V_FAB_vvs", 160],
			["RHS_Mi24V_FAB_vvsc", 160],
			["RHS_Mi24V_UPK23_vdv", 160],
			["RHS_Mi24V_UPK23_vvs", 160],
			["RHS_Mi24V_UPK23_vvsc", 160],
			["RHS_Mi24V_vdv", 160],
			["RHS_Mi24V_vvs", 160],
			["RHS_Mi24V_vvsc", 160],
			["RHS_Mi24Vt_vvs", 160],
			["RHS_Mi8AMTSh_FAB_vvs", 160],
			["RHS_Mi8AMTSh_FAB_vvsc", 160],
			["RHS_Mi8AMTSh_UPK23_vvs", 160],
			["RHS_Mi8AMTSh_UPK23_vvsc", 160],
			["RHS_Mi8AMTSh_vvs", 160],
			["RHS_Mi8AMTSh_vvsc", 160],
			["RHS_Mi8AMT_vdv", 160],
			["RHS_Mi8AMT_vvs", 160],
			["RHS_Mi8AMT_vvsc", 160],
			["RHS_Mi8MTV3_FAB_vdv", 160],
			["RHS_Mi8MTV3_FAB_vvs", 160],
			["RHS_Mi8MTV3_FAB_vvsc", 160],
			["RHS_Mi8MTV3_UPK23_vdv", 160],
			["RHS_Mi8MTV3_vdv", 160],
			["RHS_Mi8amt_civilian", 160],
			["RHS_Mi8mt_Cargo_vdv", 160],
			["RHS_Mi8mt_Cargo_vv", 160],
			["RHS_Mi8mt_Cargo_vvsc", 160],
			["RHS_Mi8mt_vdv", 160],
			["RHS_Mi8mt_vv", 160],
			["RHS_Mi8mt_vvs", 160],
			["RHS_Mi8mt_vvsc", 160],
			["RHS_Mi24Vt_vvsc", 160],
			["RHS_Mi8MTV3_heavy_vdv", 160],
			["RHS_Mi8MTV3_heavy_vvs", 160],
			["RHS_Mi8MTV3_heavy_vvsc", 160],
			["RHS_Mi8mtv3_Cargo_vdv", 160],
			["RHS_Mi8mtv3_Cargo_vvs", 160],
			["RHS_Mi8mtv3_Cargo_vvsc", 160],
			["RHS_UH1Y", 160],
			["RHS_UH1Y_FFAR", 160],
			["RHS_UH1Y_FFAR_d", 160],
			["RHS_UH1Y_UNARMED_d", 160],
			["RHS_UH1Y_d", 160],
			["RHS_UH60M", 160],
			["RHS_UH60M_MEV", 160],
			["RHS_UH60M_MEV2", 160],
			["RHS_UH60M_MEV_d", 160],
			["RHS_UH60M_d", 160],
			["RHS_Ural_Flat_MSV_01", 240],
			["RHS_Ural_Flat_VDV_01", 240],
			["RHS_Ural_Flat_VMF_01", 240],
			["RHS_Ural_Flat_VV_01", 240],
			["RHS_Ural_Fuel_MSV_01", 240],
			["RHS_Ural_Fuel_VDV_01", 240],
			["RHS_Ural_Fuel_VMF_01", 240],
			["RHS_Ural_Fuel_VV_01", 240],
			["RHS_Ural_MSV_01", 240],
			["RHS_Ural_Open_Civ_01", 240],
			["RHS_Ural_Open_Civ_02", 240],
			["RHS_Ural_Open_Civ_03", 240],
			["RHS_Ural_Open_Flat_MSV_01", 240],
			["RHS_Ural_Open_Flat_VDV_01", 240],
			["RHS_Ural_Open_Flat_VMF_01", 240],
			["RHS_Ural_Open_Flat_VV_01", 240],
			["RHS_Ural_Open_MSV_01", 240],
			["RHS_Ural_Open_VDV_01", 240],
			["RHS_Ural_Open_VMF_01", 240],
			["RHS_Ural_Open_VV_01", 240],
			["RHS_Ural_VDV_01", 240],
			["RHS_Ural_VMF_01", 240],
			["RHS_Ural_VV_01", 240],
			["RHS_Civ_Truck_02_covered_F", 240],
			["RHS_Civ_Truck_02_transport_F", 240],
			["RHS_Ural_Civ_01", 240],
			["RHS_Ural_Civ_02", 240],
			["RHS_Ural_Civ_03", 240],
			["RHS_Ural_Repair_MSV_01", 240],
			["RHS_Ural_Repair_VDV_01", 240],
			["RHS_Ural_Repair_VMF_01", 240],
			["RHS_Ural_Repair_VV_01", 240],
			["rhs_Mi8mt_cargo_vvs", 160],
			["rhs_UH1Y_unarmed", 160],
			["rhs_UH60M_MEV2_d", 160],
			["rhs_bmp3_late_msv", 160],
			["rhs_bmp3mera_msv", 160],
			["rhs_btr60_chdkz", 160],
			["rhs_btr60_msv", 160],
			["rhs_btr60_vdv", 160],
			["rhs_btr60_vmf", 160],
			["rhs_btr60_vv", 160],
			["rhs_btr70_chdkz", 160],
			["rhs_gaz66_ammo_msv", 160],
			["rhs_gaz66_ammo_vdv", 160],
			["rhs_gaz66_ammo_vmf", 160],
			["rhs_gaz66_ammo_vv", 160],
			["rhs_gaz66_ap2_msv", 160],
			["rhs_gaz66_ap2_vdv", 160],
			["rhs_gaz66_ap2_vmf", 160],
			["rhs_gaz66_ap2_vv", 160],
			["rhs_gaz66_flat_msv", 160],
			["rhs_gaz66_flat_vdv", 160],
			["rhs_gaz66_flat_vmf", 160],
			["rhs_gaz66_flat_vv", 160],
			["rhs_gaz66_msv", 160],
			["rhs_gaz66_r142_msv", 160],
			["rhs_gaz66_r142_vdv", 160],
			["rhs_gaz66_r142_vmf", 160],
			["rhs_gaz66_r142_vv", 160],
			["rhs_gaz66_repair_msv", 160],
			["rhs_gaz66_repair_vdv", 160],
			["rhs_gaz66_repair_vmf", 160],
			["rhs_gaz66_repair_vv", 160],
			["rhs_gaz66_vdv", 160],
			["rhs_gaz66_vmf", 160],
			["rhs_gaz66_vv", 160],
			["rhs_gaz66o_flat_msv", 160],
			["rhs_gaz66o_flat_vdv", 160],
			["rhs_gaz66o_flat_vmf", 160],
			["rhs_gaz66o_flat_vv", 160],
			["rhs_gaz66o_msv", 160],
			["rhs_gaz66o_vdv", 160],
			["rhs_gaz66o_vmf", 160],
			["rhs_gaz66o_vv", 160],
			["rhs_ka60_c", 160],
			["rhs_ka60_grey", 160],
			["rhs_mi28n_s13_vvs", 160],
			["rhs_mi28n_s13_vvsc", 160],
			["rhs_mi28n_vvs", 160],
			["rhs_mi28n_vvsc", 160],
			["rhs_t72bc_tv", 160],
			["rhs_tigr_3camo_vdv", 160],
			["rhs_tigr_3camo_vmf", 160],
			["rhs_tigr_3camo_vv", 160],
			["rhs_tigr_ffv_3camo_msv", 160],
			["rhs_tigr_ffv_3camo_vdv", 160],
			["rhs_tigr_ffv_3camo_vmf", 160],
			["rhs_tigr_ffv_3camo_vv", 160],
			["rhs_tigr_ffv_msv", 160],
			["rhs_tigr_ffv_vdv", 160],
			["rhs_tigr_ffv_vmf", 160],
			["rhs_tigr_ffv_vv", 160],
			["rhs_tigr_m_3camo_msv", 160],
			["rhs_tigr_m_3camo_vdv", 160],
			["rhs_tigr_m_3camo_vmf", 160],
			["rhs_tigr_m_3camo_vv", 160],
			["rhs_tigr_m_msv", 160],
			["rhs_tigr_m_vdv", 160],
			["rhs_tigr_m_vmf", 160],
			["rhs_tigr_m_vv", 160],
			["rhs_tigr_msv", 160],
			["rhs_tigr_sts_3camo_msv", 160],
			["rhs_tigr_sts_3camo_vdv", 160],
			["rhs_tigr_sts_3camo_vmf", 160],
			["rhs_tigr_sts_3camo_vv", 160],
			["rhs_tigr_sts_msv", 160],
			["rhs_tigr_sts_vdv", 160],
			["rhs_tigr_sts_vmf", 160],
			["rhs_tigr_sts_vv", 160],
			["rhs_tigr_vdv", 160],
			["rhs_tigr_vmf", 160],
			["rhs_tigr_vv", 160],
			["rhs_truck", 160],
			["rhs_typhoon_vdv", 160],
			["rhs_uaz_ags_chdkz", 160],
			["rhs_uaz_dshkm_chdkz", 160],
			["rhs_uaz_open_chdkz", 160],
			["rhs_uaz_open_vmf", 160],
			["rhs_uaz_spg9_chdkz", 160],
			["rhs_uaz_vmf", 160],
			["RHS_UAZ_MSV_01", 160],
			["rhs_uaz_open_MSV_01", 160],
			["rhs_uaz_open_vdv", 160],
			["rhs_uaz_open_vv", 160],
			["rhs_uaz_vdv", 160],
			["rhs_uaz_vv", 160],
			["rhs_kamaz5350", 160],
			["rhs_kamaz5350_flatbed", 160],
			["rhs_kamaz5350_flatbed_cover", 160],
			["rhs_kamaz5350_flatbed_cover_msv", 160],
			["rhs_kamaz5350_flatbed_cover_vdv", 160],
			["rhs_kamaz5350_flatbed_cover_vmf", 160],
			["rhs_kamaz5350_flatbed_cover_vv", 160],
			["rhs_kamaz5350_flatbed_msv", 160],
			["rhs_kamaz5350_flatbed_vdv", 160],
			["rhs_kamaz5350_flatbed_vmf", 160],
			["rhs_kamaz5350_flatbed_vv", 160],
			["rhs_kamaz5350_msv", 160],
			["rhs_kamaz5350_open", 160],
			["rhs_kamaz5350_open_msv", 160],
			["rhs_kamaz5350_open_vdv", 160],
			["rhs_kamaz5350_open_vmf", 160],
			["rhs_kamaz5350_open_vv", 160],
			["rhs_kamaz5350_vdv", 160],
			["rhs_kamaz5350_vmf", 160],
			["rhs_kamaz5350_vv", 160],
			["rhs_ural_chdkz", 160],
			["rhs_ural_open_chdkz", 160],
			["rhs_ural_work_chdkz", 160],
			["rhs_ural_work_open_chdkz", 160],
			["rhsusf_CH53E_USMC", 220],
			["rhsusf_CH53E_USMC", 240],
			["rhsusf_CH53E_USMC_D", 240],
			["rhsusf_M1078A1P2_B_CP_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_D_CP_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_M2_D_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_M2_D_open_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_M2_WD_open_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_M2_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_M2_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_M2_open_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_WD_CP_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_d_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_d_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_d_open_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_open_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_wd_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_wd_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_B_wd_open_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_d_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_d_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_d_open_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_open_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_wd_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_wd_fmtv_usarmy", 160],
			["rhsusf_M1078A1P2_wd_open_fmtv_usarmy", 160],
			["rhsusf_M1078A1R_SOV_M2_D_fmtv_socom", 160],
			["rhsusf_M1078A1R_SOV_M2_WD_fmtv_socom", 160],
			["rhsusf_M1083A1P2_B_D_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_D_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_D_open_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_D_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_D_open_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_WD_open_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_d_MHQ_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_d_Medical_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_open_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_wd_MHQ_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_wd_Medical_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_M2_wd_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_WD_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_WD_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_WD_open_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_B_open_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_D_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_D_open_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_WD_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_WD_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_WD_open_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_flatbed_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_fmtv_usarmy", 160],
			["rhsusf_M1083A1P2_open_fmtv_usarmy", 160],
			["rhsusf_M1084A1P2_B_D_fmtv_usarmy", 160],
			["rhsusf_M1084A1P2_B_M2_D_fmtv_usarmy", 160],
			["rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy", 160],
			["rhsusf_M1084A1P2_B_M2_fmtv_usarmy", 160],
			["rhsusf_M1084A1P2_B_WD_fmtv_usarmy", 160],
			["rhsusf_M1084A1P2_B_fmtv_usarmy", 160],
			["rhsusf_M1084A1P2_D_fmtv_usarmy", 160],
			["rhsusf_M1084A1P2_WD_fmtv_usarmy", 160],
			["rhsusf_M1084A1P2_fmtv_usarmy", 160],
			["rhsusf_M1084A1R_SOV_M2_D_fmtv_socom", 160],
			["rhsusf_M1084A1R_SOV_M2_WD_fmtv_socom", 160],
			["rhsusf_M1085A1P2_B_D_Medical_fmtv_usarmy", 160],
			["rhsusf_M1085A1P2_B_Medical_fmtv_usarmy", 160],
			["rhsusf_M1232_M2_usarmy_wd", 160],
			["rhsusf_M1232_MK19_usarmy_d", 160],
			["rhsusf_M1232_MK19_usarmy_wd", 160],
			["rhsusf_M1232_usarmy_d", 160],
			["rhsusf_M1232_usarmy_wd", 160],
			["rhsusf_M1237_M2_usarmy_d", 160],
			["rhsusf_M1237_M2_usarmy_wd", 160],
			["rhsusf_M1237_MK19_usarmy_d", 160],
			["rhsusf_M1237_MK19_usarmy_wd", 160],
			["rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d", 160],
			["rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd", 160],
			["rhsusf_M977A4_AMMO_BKIT_usarmy_d", 160],
			["rhsusf_M977A4_AMMO_BKIT_usarmy_wd", 160],
			["rhsusf_M977A4_AMMO_usarmy_d", 160],
			["rhsusf_M977A4_AMMO_usarmy_wd", 160],
			["rhsusf_M977A4_BKIT_M2_usarmy_d", 160],
			["rhsusf_M977A4_BKIT_M2_usarmy_wd", 160],
			["rhsusf_M977A4_BKIT_usarmy_d", 160],
			["rhsusf_M977A4_BKIT_usarmy_wd", 160],
			["rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d", 160],
			["rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd", 160],
			["rhsusf_M977A4_REPAIR_BKIT_usarmy_d", 160],
			["rhsusf_M977A4_REPAIR_BKIT_usarmy_wd", 160],
			["rhsusf_M977A4_REPAIR_usarmy_d", 160],
			["rhsusf_M977A4_REPAIR_usarmy_wd", 160],
			["rhsusf_M977A4_usarmy_d", 160],
			["rhsusf_M977A4_usarmy_wd", 160],
			["rhsusf_M978A4_BKIT_usarmy_d", 160],
			["rhsusf_M978A4_BKIT_usarmy_wd", 160],
			["rhsusf_M978A4_usarmy_d", 160],
			["rhsusf_M978A4_usarmy_wd", 160],
			["rhsusf_m1025_d", 160],
			["rhsusf_m1025_d_Mk19", 160],
			["rhsusf_m1025_d_m2", 160],
			["rhsusf_m1025_d_s", 160],
			["rhsusf_m1025_d_s_Mk19", 160],
			["rhsusf_m1025_d_s_m2", 160],
			["rhsusf_m1025_w", 160],
			["rhsusf_m1025_w_m2", 160],
			["rhsusf_m1025_w_mk19", 160],
			["rhsusf_m1025_w_s", 160],
			["rhsusf_m1025_w_s_Mk19", 160],
			["rhsusf_m1025_w_s_m2", 160],
			["rhsusf_m113_usarmy_M240", 160],
			["rhsusf_m113_usarmy_MK19", 160],
			["rhsusf_m113_usarmy_supply", 160],
			["rhsusf_m113_usarmy_unarmed", 160],
			["rhsusf_m113d_usarmy", 160],
			["rhsusf_m113d_usarmy_M240", 160],
			["rhsusf_m113d_usarmy_MK19", 160],
			["rhsusf_m113d_usarmy_medical", 160],
			["rhsusf_m113d_usarmy_supply", 160],
			["rhsusf_m113d_usarmy_unarmed", 160],
			["rhsusf_m1a1aimwd_usarmy", 160],
			["rhsusf_m1a2sep1tuskiiwd_usarmy", 160],
			["rhsusf_m998_d_2dr", 160],
			["rhsusf_m998_d_2dr_fulltop", 160],
			["rhsusf_m998_d_2dr_halftop", 160],
			["rhsusf_m998_d_4dr", 160],
			["rhsusf_m998_d_4dr_fulltop", 160],
			["rhsusf_m998_d_4dr_halftop", 160],
			["rhsusf_m998_d_s_2dr", 160],
			["rhsusf_m998_d_s_2dr_fulltop", 160],
			["rhsusf_m998_d_s_2dr_halftop", 160],
			["rhsusf_m998_d_s_4dr", 160],
			["rhsusf_m998_d_s_4dr_fulltop", 160],
			["rhsusf_m998_d_s_4dr_halftop", 160],
			["rhsusf_m998_w_2dr", 160],
			["rhsusf_m998_w_2dr_fulltop", 160],
			["rhsusf_m998_w_2dr_halftop", 160],
			["rhsusf_m998_w_4dr", 160],
			["rhsusf_m998_w_4dr_fulltop", 160],
			["rhsusf_m998_w_4dr_halftop", 160],
			["rhsusf_m998_w_s_2dr", 160],
			["rhsusf_m998_w_s_2dr_fulltop", 160],
			["rhsusf_m998_w_s_2dr_halftop", 160],
			["rhsusf_m998_w_s_4dr", 160],
			["rhsusf_m998_w_s_4dr_fulltop", 160],
			["rhsusf_m998_w_s_4dr_halftop", 160],
			["rhsusf_mrzr4_d", 160],
			["rhsusf_mrzr4_d_mud", 160],
			["rhsusf_mrzr4_w", 160],
			["rhsusf_mrzr4_w_mud", 160],
			["rhsusf_rg33_d", 160],
			["rhsusf_rg33_m2_d", 160],
			["rhsusf_rg33_m2_usmc_d", 160],
			["rhsusf_rg33_m2_usmc_wd", 160],
			["rhsusf_rg33_m2_wd", 160],
			["rhsusf_rg33_usmc_d", 160],
			["rhsusf_rg33_usmc_wd", 160],
			["rhsusf_rg33_wd", 160],
			["volha_Civ_01", 80],
			["volha_Civ_02", 80],
			["volha_Civ_03", 80]
	];

/**
 * List of class names of objects which can be loaded in transport vehicle/cargo.
 * The second element of the nested arrays is the cost capacity (in relation with the capacity of the vehicles).
 */
R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
	[
		["Exile_Bike_QuadBike_Black", 45],
		["Exile_Bike_QuadBike_Blue", 45],
		["Exile_Bike_QuadBike_Red", 45],
		["Exile_Bike_QuadBike_White", 45],
		["Exile_Bike_QuadBike_Nato", 45],
		["Exile_Bike_QuadBike_Csat", 45],
		["Exile_Bike_QuadBike_Fia", 45],
		["Exile_Bike_QuadBike_Guerilla01", 45],
		["Exile_Bike_QuadBike_Guerilla02", 45],
		["B_G_Quadbike_01_F", 45],
		["B_Quadbike_01_F", 45],
		["O_G_Quadbike_01_F", 45],
		["O_Quadbike_01_F", 45],
		["I_Quadbike_01_F", 45],
		["I_G_Quadbike_01_F", 45],
		["C_Quadbike_01_F", 45],
		["C_Quadbike_01_black_F", 45],
		["C_Quadbike_01_blue_F", 45],
		["C_Quadbike_01_red_F", 45],
		["C_Quadbike_01_white_F", 45],
		["C_Kart_01_Blu_F", 40],
		["C_Kart_01_F", 40],
		["C_Kart_01_Fuel_F", 40],
		["C_Kart_01_Red_F", 40],
		["C_Kart_01_Vrana_F", 40],
		["C_Kart_01_black_F", 40],
		["C_Kart_01_green_F", 40],
		["C_Kart_01_orange_F", 40],
		["C_Kart_01_white_F", 40],
		["C_Kart_01_yellow_F", 40],
		["Exile_Car_Kart_BluKing", 40],
		["Exile_Car_Kart_RedStone", 40],
		["Exile_Car_Kart_Vrana", 40],
		["Exile_Car_Kart_Green", 40],
		["Exile_Car_Kart_Blue", 40],
		["Exile_Car_Kart_Orange", 40],
		["Exile_Car_Kart_White", 40],
		["Exile_Car_Kart_Yellow", 40],
		["Exile_Car_Kart_Black", 40],
		["Exile_Bike_OldBike", 20],
		["Exile_Bike_MountainBike", 20],
		["ASC_B_box", 40],
		["B_CargoNET_01_F", 40],
		["B_CargoNet_01_ammo_F", 40],
		["B_supplyCrate_F", 40],
		["Box_East_AmmoOrd_F", 40],
		["Box_East_AmmoVeh_F", 40],
		["Box_East_Ammo_F", 40],
		["Box_East_Grenades_F", 40],
		["Box_East_Support_F", 40],
		["Box_East_WpsLaunch_F", 40],
		["Box_East_WpsSpecial_F", 40],
		["Box_East_Wps_F", 40],
		["Box_IND_AmmoOrd_F", 40],
		["Box_IND_AmmoVeh_F", 40],
		["Box_IND_Ammo_F", 40],
		["Box_IND_Grenades_F", 40],
		["Box_IND_Support_F", 40],
		["Box_IND_WpsLaunch_F", 40],
		["Box_IND_WpsSpecial_F", 40],
		["Box_IND_Wps_F", 40],
		["Box_NATO_AmmoOrd_F", 40],
		["Box_NATO_AmmoVeh_F", 40],
		["Box_NATO_Ammo_F", 40],
		["Box_NATO_Grenades_F", 40],
		["Box_NATO_Support_F", 40],
		["Box_NATO_WpsLaunch_F", 40],
		["Box_NATO_WpsSpecial_F", 40],
		["Box_NATO_Wps_F", 40],
		["C_supplyCrate_F", 40],
		["CargoNet_01_box_F", 40],
		["Exile_Container_SupplyBox", 40],
		["IG_supplyCrate_F", 40],
		["I_CargoNET_01_F", 40],
		["I_CargoNet_01_ammo_F", 40],
		["I_supplyCrate_F", 40],
		["Land_CargoBox_V1_F", 40],
		["O_CargoNET_01_F", 40],
		["O_CargoNet_01_ammo_F", 40],
		["O_supplyCrate_F", 40]
	];

/**
 * List of class names of objects which can be carried and moved by a player.
 */
R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
	[
		"ASC_B_box",
		"B_CargoNET_01_F",
		"B_CargoNet_01_ammo_F",
		"B_supplyCrate_F",
		"Box_East_AmmoOrd_F",
		"Box_East_AmmoVeh_F",
		"Box_East_Ammo_F",
		"Box_East_Grenades_F",
		"Box_East_Support_F",
		"Box_East_WpsLaunch_F",
		"Box_East_WpsSpecial_F",
		"Box_East_Wps_F",
		"Box_IND_AmmoOrd_F",
		"Box_IND_AmmoVeh_F",
		"Box_IND_Ammo_F",
		"Box_IND_Grenades_F",
		"Box_IND_Support_F",
		"Box_IND_WpsLaunch_F",
		"Box_IND_WpsSpecial_F",
		"Box_IND_Wps_F",
		"Box_NATO_AmmoOrd_F",
		"Box_NATO_AmmoVeh_F",
		"Box_NATO_Ammo_F",
		"Box_NATO_Grenades_F",
		"Box_NATO_Support_F",
		"Box_NATO_WpsLaunch_F",
		"Box_NATO_WpsSpecial_F",
		"Box_NATO_Wps_F",
		"C_supplyCrate_F",
		"CargoNet_01_box_F",
		"Exile_Bike_MountainBike",
		"Exile_Bike_OldBike",
		"Exile_Container_SupplyBox",
		"Exile_Item_CamoTentKit",
		"Exile_Item_SafeKit",
		"IG_supplyCrate_F",
		"I_CargoNET_01_F",
		"I_CargoNet_01_ammo_F",
		"I_supplyCrate_F",
		"K02",
		"K03",
		"K04",
		"Land_CargoBox_V1_F",
		"O_CargoNET_01_F",
		"O_CargoNet_01_ammo_F",
		"O_supplyCrate_F"
	];